
ALTER TABLE dbo.SMPBRANCHS ADD SAFE_BRANCH_YN varchar(1) NULL
GO
ALTER TABLE dbo.SMPBRANCHS ADD CONSTRAINT DF_SMPBRANCHS_SAFE_BRANCH_YN DEFAULT ('N') FOR SAFE_BRANCH_YN
GO
UPDATE SMPBRANCHS SET SAFE_BRANCH_YN = 'N'
GO
SELECT *
  FROM SMPBRANCHS
 WHERE BRANCHID = '304456'
GO
UPDATE SMPBRANCHS SET SAFE_BRANCH_YN = 'Y' WHERE BRANCHID = '304456'



