-- 공지게시판 
ALTER TABLE NOTICEBOARD ALTER COLUMN USER_MAIL_ADDR varchar(150)
ALTER TABLE NOTICEBOARD ALTER COLUMN USER_PHON_NUMB varchar(150)

-- 요구사항목록
ALTER TABLE MEREQU ALTER COLUMN REQU_TEL_NUMB varchar(150)

-- 참여 게시팜 답글
ALTER TABLE PARTICIPATION_COMMENT ALTER COLUMN BUSINESS_NUM varchar(150)

-- 메일관리
ALTER TABLE MAILINFO ALTER COLUMN receiveMailAddr varchar(4000)

-- VOC 게시판 - 고객의 소리
ALTER TABLE VOCBOARD ALTER COLUMN EMAIL varchar(150)
ALTER TABLE VOCBOARD ALTER COLUMN TEL varchar(150)

-- 사업장
ALTER TABLE SMPBRANCHS ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN REGISTNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN PHONENUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN E_MAIL varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN POSTADDRNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN ADDRES varchar(500)
ALTER TABLE SMPBRANCHS ALTER COLUMN ADDRESDESC varchar(500)
ALTER TABLE SMPBRANCHS ALTER COLUMN FAXNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN ACCOUNTTELNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN ACCOUNTNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN SHARP_MAIL varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN EBILL_EMAIL varchar(150)

-- 사용자
ALTER TABLE SMPUSERS ALTER COLUMN TEL varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN MOBILE varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN FAX varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN ZIPCODE varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN ADDRESS1 varchar(500)
ALTER TABLE SMPUSERS ALTER COLUMN ADDRESS2 varchar(500)
ALTER TABLE SMPUSERS ALTER COLUMN EMAIL varchar(200)

-- 조직 I/F 히스토리
ALTER TABLE IFBORGSHIST ALTER COLUMN BUSINESSNUM varchar(150)

-- 비회원
ALTER TABLE SMPNONUSERS ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE SMPNONUSERS ALTER COLUMN PWD varchar(150)

-- 신규자재제안
ALTER TABLE SMPNEW_MATERSUGGEST ALTER COLUMN SUGGESTPHONE varchar(150)
ALTER TABLE SMPNEW_MATERSUGGEST ALTER COLUMN SUGGESTEMAIL varchar(150)
ALTER TABLE SMPNEW_MATERSUGGEST ALTER COLUMN SUITABLEMOBILE varchar(150)
ALTER TABLE SMPNEW_MATERSUGGEST ALTER COLUMN BUSINESSNUM varchar(150)

-- 참가신청
ALTER TABLE SMPPARTAPPL ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE SMPPARTAPPL ALTER COLUMN PHONENUM varchar(150)
ALTER TABLE SMPPARTAPPL ALTER COLUMN BUSIPHONENUM varchar(150)
ALTER TABLE SMPPARTAPPL ALTER COLUMN BUSICHARGEREMAIL varchar(150)

-- 조직배송지
ALTER TABLE SMPDELIVERYINFO ALTER COLUMN SHIPPINGPHONENUM varchar(150)
ALTER TABLE SMPDELIVERYINFO ALTER COLUMN SHIPPINGADDRES varchar(1000)

-- 사업장
ALTER TABLE SMPBRANCHS ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN REGISTNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN PHONENUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN E_MAIL varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN POSTADDRNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN ADDRES varchar(500)
ALTER TABLE SMPBRANCHS ALTER COLUMN ADDRESDESC varchar(500)
ALTER TABLE SMPBRANCHS ALTER COLUMN FAXNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN ACCOUNTTELNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN ACCOUNTNUM varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN SHARP_MAIL varchar(150)
ALTER TABLE SMPBRANCHS ALTER COLUMN EBILL_EMAIL varchar(150)

-- 사업장 요청
ALTER TABLE REQSMPBRANCHS ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN REGISTNUM varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN PHONENUM varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN E_MAIL varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN POSTADDRNUM varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN ADDRES varchar(500)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN ADDRESDESC varchar(500)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN FAXNUM varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN ACCOUNTTELNUM varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN ACCOUNTNUM varchar(150)
ALTER TABLE REQSMPBRANCHS ALTER COLUMN SHARP_MAIL varchar(150)

-- 공급사
ALTER TABLE SMPVENDORS ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN REGISTNUM varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN PHONENUM varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN E_MAIL varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN POSTADDRNUM varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN ADDRES varchar(500)
ALTER TABLE SMPVENDORS ALTER COLUMN ADDRESDESC varchar(500)
ALTER TABLE SMPVENDORS ALTER COLUMN FAXNUM varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN ACCOUNTTELNUM varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN ACCOUNTNUM varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN TRUSTBILLUSEREMAIL varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN TRUSTBILLUSERTEL varchar(150)
ALTER TABLE SMPVENDORS ALTER COLUMN SHARP_MAIL varchar(150)

-- 공급사 요청
ALTER TABLE REQSMPVENDORS ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN REGISTNUM varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN PHONENUM varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN E_MAIL varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN POSTADDRNUM varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN ADDRES varchar(500)
ALTER TABLE REQSMPVENDORS ALTER COLUMN ADDRESDESC varchar(500)
ALTER TABLE REQSMPVENDORS ALTER COLUMN FAXNUM varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN ACCOUNTTELNUM varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN ACCOUNTNUM varchar(150)
ALTER TABLE REQSMPVENDORS ALTER COLUMN SHARP_MAIL varchar(150)

-- 사용자
ALTER TABLE SMPUSERS ALTER COLUMN TEL varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN MOBILE varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN FAX varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN ZIPCODE varchar(150)
ALTER TABLE SMPUSERS ALTER COLUMN ADDRESS1 varchar(500)
ALTER TABLE SMPUSERS ALTER COLUMN ADDRESS2 varchar(500)
ALTER TABLE SMPUSERS ALTER COLUMN EMAIL varchar(150)

-- 사용자_백업
ALTER TABLE SMPUSERS_BACKUP ALTER COLUMN FAX varchar(150)
ALTER TABLE SMPUSERS_BACKUP ALTER COLUMN ZIPCODE varchar(150)
ALTER TABLE SMPUSERS_BACKUP ALTER COLUMN ADDRESS1 varchar(500)
ALTER TABLE SMPUSERS_BACKUP ALTER COLUMN ADDRESS2 varchar(500)

-- 사용자_로그
ALTER TABLE SMPUSERS_LOG ALTER COLUMN TEL varchar(150)
ALTER TABLE SMPUSERS_LOG ALTER COLUMN MOBILE varchar(150)
ALTER TABLE SMPUSERS_LOG ALTER COLUMN FAX varchar(150)
ALTER TABLE SMPUSERS_LOG ALTER COLUMN ZIPCODE varchar(150)
ALTER TABLE SMPUSERS_LOG ALTER COLUMN ADDRESS1 varchar(500)
ALTER TABLE SMPUSERS_LOG ALTER COLUMN ADDRESS2 varchar(500)
ALTER TABLE SMPUSERS_LOG ALTER COLUMN EMAIL varchar(150)

-- 장바구니
ALTER TABLE MRCART ALTER COLUMN TRAN_TELE_NUMB varchar(150)

-- 주문
ALTER TABLE MRORDM ALTER COLUMN ORDE_TELE_NUMB varchar(150)
ALTER TABLE MRORDM ALTER COLUMN TRAN_DATA_ADDR varchar(500)
ALTER TABLE MRORDM ALTER COLUMN TRAN_TELE_NUMB varchar(150)
ALTER TABLE MRORDM ALTER COLUMN MANA_TELE_NUMB varchar(150)

-- 품질관리 VOC
ALTER TABLE SMPVOC ALTER COLUMN BUSINESSNUM varchar(150)
ALTER TABLE SMPVOC ALTER COLUMN REQTEL varchar(150)

-- 품질경영평가 
-- ALTER TABLE SMPEVAL ALTER COLUMN BUSINESSNUM varchar(150)
-- 개체탐색기에서 수동으로 변환해야함( SMPEVAL )

-- 저장 후 SET ANSI_PADDING OFF; 해줘야함

-- 소싱관리 공급사
-- ALTER TABLE SMPSOURCINGVENDOR ALTER COLUMN BUSINESSNUM varchar(150)
-- 개체탐색기에서 수동으로 변환해야함 ( SMPSOURCINGVENDOR ) 

-- 품질관리 공급사
-- ALTER TABLE SMPQUALITYVENDOR ALTER COLUMN BUSINESSNUM varchar(150)
-- 개체탐색기에서 수동으로 변환해야함 ( SMPQUALITYVENDOR )
