CREATE TABLE ADJ_SALES_MAST (
	SELL_SEQU_NO varchar(10) NOT NULL COMMENT '매출ID',
	CLIENT_ID varchar(10) DEFAULT 0 NOT NULL COMMENT '법인ID',
	BRANCH_ID varchar(10) DEFAULT 0 NULL COMMENT '사업장ID',
	SELL_SEQU_NM varchar(200) NULL COMMENT '정산명',
	ADJ_INSERT_USER_ID varchar(100) NULL COMMENT '정산생성자ID',
	ADJ_INSERT_DT datetime NULL COMMENT '정산생성일시',
	ADJ_CONFIRM_USER_ID varchar(10) NULL COMMENT '매출확정자',
	ADJ_CONFIRM_DT datetime NULL COMMENT '매출확정일시',
	ADJ_CLOSE_DT datetime NULL COMMENT '매출마감일시',
	ADJ_SELL_AMT decimal(15,2) NULL COMMENT '매출금액',
	ADJ_SELL_TAX decimal(15,2) NULL COMMENT '부가세',
	ADJ_SELL_TOTAL_AMT decimal(15,2) NULL COMMENT '매출합계',
	SLIP_NO varchar(20) NULL COMMENT '전표번호',
	EXPIRE_DT datetime NULL COMMENT '만기일시',
	SLIP_SEND_DT datetime NULL COMMENT '매출 전송일시',
	SLIP_SEND_USER_ID varchar(10) NULL COMMENT '매출전송자ID',
	REPAY_NO varchar(20) NULL COMMENT '반제번호',
	REPAY_AMT decimal(15,2) NULL COMMENT '반제금액',
	BOND_ST varchar(10) not null default 0 COMMENT '채권상태',
	PAY_BILL_TP_CD varchar(20) NULL COMMENT '지급조건 (PAYMCONDCODE)',
	OVER_MONTH varchar(10) NULL COMMENT '경과월',
	OVER_DAY varchar(10) NULL COMMENT '초과일수',
	REPAY_DONE_DT datetime NULL COMMENT '반제완료일시',
	INSERT_BORG_ID varchar(10) NULL COMMENT '정산생성업체ID',
	IS_TRANSFER varchar(10) DEFAULT 1 NULL COMMENT '이관여부',
	TRANSFER_DT datetime NULL COMMENT '이관일시',
	ADJ_APP_YN char(1) not null default 'N' COMMENT '매출승인',
	ADJ_APP_USER_ID varchar(10) NULL COMMENT '매출승인자',
	ADJ_APP_DT datetime NULL COMMENT '매출승인날짜',
	TAX_CD varchar(10) DEFAULT '10' NOT NULL COMMENT '과세구분 (VTAXTYPECODE)',
	TEMP_ADJ_CLOSE_DT varchar(10) NULL COMMENT '임시세금계산서일',
	TEMP_ADJ_USER_ID varchar(10) NULL COMMENT '임시저장자',
	TEMP_ADJ_DT datetime NULL COMMENT '임시저장일시',
	ADJ_BUY_AMT decimal(15,2) NULL COMMENT '매입금액',
	SEND_YN char(1) not null default 'N' COMMENT '전송여부',
	PRIMARY KEY (SELL_SEQU_NO)
)
COMMENT = '매출헤더';

CREATE TABLE ADJ_SALES_CANCEL_HIST (
	SELL_SEQU_NO varchar(10) NOT NULL COMMENT '매출ID',
	CLIENT_ID varchar(10) NOT NULL COMMENT '법인ID',
	BRANCH_ID varchar(10) NULL COMMENT '사업장ID',
	SELL_SEQU_NM varchar(200) NULL COMMENT '정산명',
	ADJ_INSERT_USER_ID varchar(100) NULL COMMENT '정산생성자ID',
	ADJ_INSERT_DT datetime NULL COMMENT '정산생성일시',
	ADJ_CONFIRM_USER_ID varchar(10) NULL COMMENT '매출확정자ID',
	ADJ_CONFIRM_DT datetime NULL COMMENT '매출확정일시',
	ADJ_CLOSE_DT datetime NULL COMMENT '매출마감일시',
	ADJ_SELL_AMT decimal(15,2) NULL COMMENT '매출금액',
	ADJ_SELL_TAX decimal(15,2) NULL COMMENT '부가세',
	ADJ_SELL_TOTAL_AMT decimal(15,2) NULL COMMENT '매출합계',
	SLIP_NO varchar(20) NULL COMMENT '전표번호',
	EXPIRE_DT datetime NULL COMMENT '만기일시',
	SLIP_SEND_DT datetime NULL COMMENT '매출 전송일시',
	SLIP_SEND_USER_ID varchar(10) NULL COMMENT '매출전송자ID',
	REPAY_NO varchar(20) NULL COMMENT '반제번호',
	REPAY_AMT decimal(15,2) NULL COMMENT '반제금액',
	BOND_ST varchar(10) NULL COMMENT '채권상태',
	PAY_TERMS_CD varchar(20) NULL COMMENT '지급조건',
	OVER_MONTH varchar(10) NULL COMMENT '경과월',
	OVER_DAY varchar(10) NULL COMMENT '초과일수',
	REPAY_DONE_DT datetime NULL COMMENT '반제완료일시',
	INSERT_BORG_ID varchar(10) NULL COMMENT '정산생성업체ID',
	CANCEL_USER_ID varchar(10) NULL COMMENT '전송취소자ID',
	CANCEL_DT datetime NULL COMMENT '전송취소일',
	REPAY_SLIP_NO varchar(20) NULL COMMENT '반제전표번호'
)
COMMENT = '매출전송취소 이력';

CREATE TABLE ADJ_SALES_RECOVERY (
	BOND_RECE_NO varchar(10) NOT NULL COMMENT '채권발생회수ID',
	SELL_SEQU_NO varchar(10) NOT NULL COMMENT '매출id',
	INSERT_DT datetime NULL COMMENT '작성일시',
	ALRAM_DT datetime NULL COMMENT '알람일시',
	ALRAM_RECE_USER_ID varchar(10) NULL COMMENT '알람수신자ID',
	CONTEXT TEXT NULL COMMENT '내용',
	REPAY_AMT decimal(15,2) NULL COMMENT '반제금액',
	INSERT_USER_ID varchar(10) NULL COMMENT '작성자',
	RECEIPT_DT datetime NULL COMMENT '입금예상일시',
	RECEIPT_AMT decimal(18,2) NULL COMMENT '입금예상금액',
	CALLED_USER_NM varchar(50) NULL COMMENT '통화자',
	RECEIPT_ST varchar(100) NULL COMMENT '입금유형',
	PRIMARY KEY (BOND_RECE_NO)
)
COMMENT = '채권회수내역';

CREATE TABLE ADJ_BUYING_MAST (
	BUY_SEQU_NO varchar(10) NOT NULL COMMENT '매입ID',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	ADJ_CONFIRM_USER_ID varchar(10) NULL COMMENT '매입확정자',
	ADJ_CONFIRM_DT datetime NULL COMMENT '매입확정일시',
	ADJ_CLOSE_DT datetime NULL COMMENT '매입마감일시',
	ADJ_BUY_AMT decimal(15,2) NULL COMMENT '매입금액',
	ADJ_BUY_TAX decimal(15,2) NULL COMMENT '매입부가세',
	ADJ_SELL_TOTAL_AMT decimal(15,2) NULL COMMENT '매입합계',
	SLIP_NO varchar(20) NULL COMMENT '전표번호',
	EXPIRE_DT datetime NULL COMMENT '만기일시',
	SLIP_SEND_DT datetime NULL COMMENT '매입전송일시',
	SLIP_SEND_USER_ID varchar(10) NULL COMMENT '매입전송자ID',
	REPAY_NO varchar(20) NULL COMMENT '반제번호',
	REPAY_AMT decimal(15,2) NULL COMMENT '반제금액',
	BOND_ST varchar(10) null default 0 COMMENT '채무상태',
	PAY_BILL_TP_CD varchar(20) NULL COMMENT '지급조건 (PAYMCONDCODE)',
	OVER_MONTH varchar(10) NULL COMMENT '경과월',
	OVER_DAY varchar(10) NULL COMMENT '초과일수',
	REPAY_DONE_DT datetime NULL COMMENT '반제완료일시',
	INSERT_BORG_ID varchar(10) NULL COMMENT '정산생성업체ID',
	ETC_DATE varchar(18) NULL COMMENT '전자외담발생일',
	ETC_EXPIRE_DT datetime NULL COMMENT '외담대만기도래일',
	SUMMARY varchar(2000) NULL COMMENT '적요',
	TAX_CD varchar(10) DEFAULT '10' NOT NULL COMMENT '과세구분 (VTAXTYPECODE)',
	PRE_BUY_YN VARchar(1) not null default 'N' COMMENT '선매입YN',
	COST_APPLY_YN VARchar(1) not null default 'N' COMMENT '원가반영여부',
	SEND_YN VARchar(1) not NULL default 'N' COMMENT '전송여부',
	DELI_AMT decimal(15,0) DEFAULT '0' NULL COMMENT '배송금액',
	PRIMARY KEY (BUY_SEQU_NO)
)
COMMENT = '매입헤더';

CREATE TABLE ADJ_BUYING_PAY (
	BOND_RECE_NO varchar(10) NOT NULL COMMENT '채무발생회수ID',
	BUY_SEQU_NO varchar(10) NOT NULL COMMENT '매입ID',
	INSERT_DT datetime NULL COMMENT '작성일시',
	ALRAM_DT datetime NULL COMMENT '알람일시',
	ALRAM_RECE_USER_ID varchar(10) NULL COMMENT '알람수신자ID',
	CONTEXT TEXT NULL COMMENT '내용',
	REPAY_AMT decimal(15,2) NULL COMMENT '반제금액',
	INSERT_USER_ID varchar(10) NULL COMMENT '작성자',
	RECEIPT_DT datetime NULL COMMENT '출금예상일시',
	RECEIPT_AMT decimal(18,0) NULL COMMENT '출금예상금액',
	CALLED_USER_NM varchar(50) NULL COMMENT '통화자',
	PRIMARY KEY (BOND_RECE_NO)
)
COMMENT = '채무지급내역';
