CREATE TABLE B2C_GOODS_VENDOR (
	GOOD_IDEN_NO varchar(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	SALE_YN varchar(1) DEFAULT 'N' NOT NULL COMMENT '할인여부_Default:N',
	SELL_PRICE decimal(15,2) NOT NULL COMMENT '판매가_할인가',
	ORI_SELL_PRICE decimal(15,2) DEFAULT 0 NULL COMMENT '원판매가',
	REPRE_GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '대표상품코드',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일시',
	UPDATE_USER_ID varchar(20) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (GOOD_IDEN_NO, VENDOR_ID)
) 
COMMENT = '상품공급사_B2C';

CREATE TABLE B2C_GOODS_VENDOR_ASK (
	ASK_ID int NOT NULL COMMENT '문의ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '공급사ID',
	VENDOR_ID varchar(10) NOT NULL COMMENT '상품코드',
	ASK_DESC varchar(500) NOT NULL COMMENT '문의 내용',
	ANSWER_DESC varchar(500) NOT NULL COMMENT '답변내용',
	ASK_ST varchar(1) DEFAULT '0' NOT NULL COMMENT '답변 상태',
	HIDDEN_YN varchar(1) DEFAULT 'N' NULL COMMENT '비밀글 여부_ Default : N',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일시',
	UPDATE_USER_ID varchar(10) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (ASK_ID)
) 
COMMENT = '상품공급사_B2C_상품문의';

CREATE TABLE B2C_GOODS_VENDOR_HIST (
	INSERT_DT DATETIME NOT NULL COMMENT '등록일시',
	GOOD_IDEN_NO varchar(20) NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	SALE_YN varchar(1) DEFAULT 'N' NULL COMMENT '할인여부_Default:N',
	SELL_PRICE decimal(15,2) DEFAULT 0 NULL COMMENT '판매가_할인가', 
	ORI_SELL_PRICE decimal(15,2) DEFAULT 0 NULL COMMENT '원판매가',
	REPRE_GOOD_IDEN_NO varchar(20) NULL COMMENT '대표상품코드', 
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	UPDATE_USER_ID varchar(10) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (INSERT_DT)
) 
COMMENT = '상품공급사_B2C_HIST';

CREATE TABLE B2C_GOODS_VENDOR_NOTI (
	GOOD_IDEN_NO varchar(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	PACKAGE_YN VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '상품코드',
	GOODS_NOTI_YN varchar(1) DEFAULT 'N' NOT NULL COMMENT '상품고시정보체크여부_Default: N',
	GOODS_NM varchar(200) NULL COMMENT '품명 및 모델명',
	GOODS_LAW varchar(200) NULL COMMENT '법에의한사항',
	GOODS_COUNTRY varchar(100) NULL COMMENT '제조국또는원산지',
	GOODS_MAN varchar(50) NULL COMMENT '제조자',
	GOODS_AS_TEL_NO varchar(50) NULL COMMENT 'A/S 책임자 전화번호',
	META_TAG varchar(400) NULL COMMENT '메타태그',
	ALT_IMG_TEXT varchar(100) NULL COMMENT '상품 이미지 ALT 텍스트',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	UPDATE_USER_ID varchar(20) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (GOOD_IDEN_NO, VENDOR_ID)
) 
COMMENT = '상품공급사_B2C_고시정보';

CREATE TABLE B2C_ORD_RETURN_ATTACH (
	RETU_IDEN_NO int NOT NULL COMMENT '반품번호',
	CHANGE_RETURN_TP varchar(20) DEFAULT 'RETURN' NULL COMMENT '교환반품구분',
	REQ_REASON TEXT NULL COMMENT '요청사유상세',
	ATTACH_SEQ1 int NULL COMMENT '첨부1 ID',
	ATTACH_SEQ2 int NULL COMMENT '첨부2 ID',
	ATTACH_SEQ3 int NULL COMMENT '첨부3 ID',
	ATTACH_SEQ4 int NULL COMMENT '첨부4 ID',
	ATTACH_SEQ5 int NULL COMMENT '첨부5 ID',
	PRIMARY KEY (RETU_IDEN_NO)
) 
COMMENT = 'B2C 교환반품 첨부';

CREATE TABLE B2C_DELIVERY_AMT (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	VENDOR_ID varchar(20) NOT NULL COMMENT '공급사ID',
	DELIVERY_AMT decimal(15,2) DEFAULT 0 NOT NULL COMMENT '배송비',
	PAY_YN varchar(1) DEFAULT 'N' NULL COMMENT '정산여부',
	ORG_DELIVERY_AMT decimal(15,2) DEFAULT 0 NOT NULL COMMENT '최초배송비',
	REFUND_NO INT NOT NULL DEFAULT 0 COMMENT '환불차수',
	BUYI_SEQU_NO VARCHAR(10) NULL COMMENT '매입ID',
	PRIMARY KEY (ORDE_IDEN_NO, VENDOR_ID, REFUND_NO)
) 
COMMENT = '주문배송비';

CREATE TABLE B2C_PAY_REFUND (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	VENDOR_ID varchar(20) NOT NULL COMMENT '공급사ID',
	REFUND_AMT decimal(15,2) DEFAULT 0 NOT NULL COMMENT '환불금액',
	REFUND_CONTENT varchar(500) NULL COMMENT '환불내역',
	RETU_IDEN_NO int NULL COMMENT '반품번호',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일시'
) 
COMMENT = '주문환불내역';

CREATE TABLE B2C_PAYMENT (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	PAYMENT_KEY_NO varchar(200) NULL COMMENT '결제번호',
	METHOD varchar(50) NULL COMMENT '결제수단',
	CARD_NO varchar(20) NULL COMMENT '카드번호',
	TOTAL_AMT decimal(15,2) NULL COMMENT '총결제금액',
	BALANCE_AMT decimal(15,2) NULL COMMENT '취소가능금액',
	REQUESTED_DT datetime NULL COMMENT '결제일시',
	APPROVED_DT datetime NULL COMMENT '승인일시',
	LAST_TRANSACTION_KEY_NO varchar(64) NULL COMMENT '마지막거래번호',
	SUPPLIED_AMT decimal(15,2) NULL COMMENT '공급사액',
	VAT decimal(15,2) NULL COMMENT '부가세액',
	PARTIAL_CANCEL_YN varchar(1) NULL COMMENT '부분취소가능여부_YN',
	MOBILE_NO varchar(15) NULL COMMENT '결제휴대폰번호',
	RECEIPT_URL varchar(300) NULL COMMENT '결제내역영수증 URL',
	CARD_TYPE_NM varchar(10) NULL COMMENT '카드종류',
	ISSUER_CODE varchar(2) NULL COMMENT '결제카드코드',
	INSTALL_MONTH int NULL COMMENT '할부개월',
	EASY_PROVIDER varchar(20) NULL COMMENT '간편결제사',
	INSERT_DT datetime NULL COMMENT '등록일시',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	ORG_AMT decimal(15,2) NULL COMMENT '최초결제금액',
	PRIMARY KEY (ORDE_IDEN_NO)
) 
COMMENT = '주문결제내역';

CREATE TABLE B2C_PAYMENT_HIST (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	PAYMENT_KEY_NO varchar(200) NULL COMMENT '결제번호',
	METHOD varchar(50) NULL COMMENT '결제수단',
	CARD_NO varchar(20) NULL COMMENT '카드번호',
	TOTAL_AMT decimal(15,2) NULL COMMENT '총결제금액',
	BALANCE_AMT decimal(15,2) NULL COMMENT '취소가능금액',
	REQUESTED_DT datetime NULL COMMENT '결제일시',
	APPROVED_DT datetime NULL COMMENT '승인일시',
	LAST_TRANSACTION_KEY_NO varchar(64) NULL COMMENT '마지막거래번호',
	SUPPLIED_AMT decimal(15,2) NULL COMMENT '공급사액',
	VAT decimal(15,2) NULL COMMENT '부가세액',
	PARTIAL_CANCEL_YN varchar(1) NULL COMMENT '부분취소가능여부_YN',
	MOBILE_NO varchar(15) NULL COMMENT '결제휴대폰번호',
	RECEIPT_URL varchar(300) NULL COMMENT '결제내역영수증 URL',
	CARD_TYPE_NM varchar(10) NULL COMMENT '카드종류',
	ISSUER_CODE varchar(2) NULL COMMENT '결제카드코드',
	INSTALL_MONTH int NULL COMMENT '할부개월',
	EASY_PROVIDER varchar(20) NULL COMMENT '간편결제사',
	INSERT_DT datetime NULL COMMENT '등록일시',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	ORG_AMT decimal(15,2) NULL COMMENT '최초결제금액'
) 
COMMENT = '주문결제내역 이력';

CREATE TABLE B2C_EXHIBITION (
	DISP_ID int NOT NULL COMMENT '기획전 ID',
	DISP_NM varchar(200) NULL COMMENT '기획전명',
	DISP_START_YMD varchar(10) NULL COMMENT '전시시작일',
	DISP_END_YMD varchar(10) NULL COMMENT '전시종료일',
	BANNER_ID varchar(10) NULL COMMENT '배너이미지ID',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일시',
	UPDATE_USER_ID varchar(20) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (DISP_ID)
) 
COMMENT = 'B2C 기획전';

CREATE TABLE B2C_EXHIBITION_GOODS (
	DISP_ID int NOT NULL COMMENT '기획전ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일시',
	PRIMARY KEY (DISP_ID, GOOD_IDEN_NO, VENDOR_ID)
) 
COMMENT = '기획전상품';

CREATE TABLE B2C_VENDORS (
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	TAC_AGREE_DT datetime NULL COMMENT '약관동의일시',
	DELI_TYPE_CD varchar(10) NULL COMMENT '배송유형_택배사코드 (DELIVERYTYPE)',
	BASE_DELI_AMT decimal(15,2) NULL COMMENT '기본배송비',
	PACKAGE_YN varchar(1) DEFAULT 'N' NULL COMMENT '묶음배송여부',    
	HILL_YN varchar(1) DEFAULT 'N' NULL COMMENT '도서산간여부',   
	JEJU_DELI_AMT decimal(15,2) DEFAULT 0 NULL COMMENT '제주배송비',    
	JEJU_OTHER_DELI_AMT decimal(15,2) DEFAULT 0 NULL COMMENT '제주 외 배송비',  
	FREE_DELI_YN varchar(1) DEFAULT 'N' NULL COMMENT '무료배송 정책여부',
	FREE_DELI_AMT decimal(15,2) DEFAULT 0 NULL COMMENT '무료배송 주문금액',       
	DEAL_CANCEL varchar(800) NULL COMMENT '주문취소정책',          
	DEAL_RETURN_FEE_POLICY varchar(800) NULL COMMENT '반품/교환 비용 정책',     
	DEAL_RETURN_PERIOD varchar(800) NULL COMMENT '반품/교환 가능 기간',     
	DEAL_RETURN_REASON varchar(800) NULL COMMENT '반품/교환 불가 사유',     
	DEAL_REFERENCE varchar(800) NULL COMMENT '참고사항',            
	DEAL_RETURN_SHIPPING_PLACE varchar(200) NULL COMMENT '반품/교환 배송지',       
	DEAL_RETURN_SHIPPING_PLACE_DTL varchar(200) NULL COMMENT '반품/교환 배송지 상세',
	DEAL_AS_TELNUM varchar(50) NULL COMMENT 'A/S관련 전화번호',     
	EMAIL varchar(100) NULL COMMENT '이메일',            
	ASK_TIME varchar(100) NULL COMMENT '고객문의 가능 시간',      
	TEL_ORDER_BUSI_NUM varchar(30) NULL COMMENT '통신판매업 신고번호',     
	REASON varchar(500) NOT NULL COMMENT '사유',          
	INSERT_USER_ID varchar(10) NOT NULL COMMENT '등록자ID',          
	INSERT_DT datetime NULL COMMENT '등록일시',            
	UPDATE_USER_ID varchar(10) NULL COMMENT '수정자ID',              
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (VENDOR_ID)
) 
COMMENT = '공급사 B2C';

CREATE TABLE B2C_VENDORS_DELIVERY_BASIS (
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	ZIP_NO varchar(10) NOT NULL COMMENT '우편번호',
	JEJU_YN varchar(1) NOT NULL COMMENT '제주여부',
	OTHER_YN varchar(1) NOT NULL COMMENT '도서산간여부',
	PRIMARY KEY (VENDOR_ID, ZIP_NO)
) 
COMMENT = 'B2C 배송 기준표';

CREATE TABLE B2C_VENDORS_HIST (
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	TAC_AGREE_DT datetime NULL COMMENT '약관동의일시',
	DELI_TYPE_CD varchar(10) NULL COMMENT '배송유형_택배사코드 (DELIVERYTYPE)',
	BASE_DELI_AMT decimal(15,2) NULL COMMENT '기본배송비',
	PACKAGE_YN varchar(1) DEFAULT 'N' NULL COMMENT '묶음배송여부',    
	HILL_YN varchar(1) DEFAULT 'N' NULL COMMENT '도서산간여부',   
	JEJU_DELI_AMT decimal(15,2) DEFAULT 0 NULL COMMENT '제주배송비',    
	JEJU_OTHER_DELI_AMT decimal(15,2) DEFAULT 0 NULL COMMENT '제주 외 배송비',  
	FREE_DELI_YN varchar(1) DEFAULT 'N' NULL COMMENT '무료배송 정책여부',
	FREE_DELI_AMT decimal(15,2) DEFAULT 0 NULL COMMENT '무료배송 주문금액',       
	DEAL_CANCEL varchar(800) NULL COMMENT '주문취소정책',          
	DEAL_RETURN_FEE_POLICY varchar(800) NULL COMMENT '반품/교환 비용 정책',     
	DEAL_RETURN_PERIOD varchar(800) NULL COMMENT '반품/교환 가능 기간',     
	DEAL_RETURN_REASON varchar(800) NULL COMMENT '반품/교환 불가 사유',     
	DEAL_REFERENCE varchar(800) NULL COMMENT '참고사항',            
	DEAL_RETURN_SHIPPING_PLACE varchar(200) NULL COMMENT '반품/교환 배송지',       
	DEAL_RETURN_SHIPPING_PLACE_DTL varchar(200) NULL COMMENT '반품/교환 배송지 상세',
	DEAL_AS_TELNUM varchar(50) NULL COMMENT 'A/S관련 전화번호',     
	EMAIL varchar(100) NULL COMMENT '이메일',            
	ASK_TIME varchar(100) NULL COMMENT '고객문의 가능 시간',      
	TEL_ORDER_BUSI_NUM varchar(30) NULL COMMENT '통신판매업 신고번호',     
	REASON varchar(500) NOT NULL COMMENT '사유',          
	INSERT_USER_ID varchar(10) NOT NULL COMMENT '등록자ID',          
	INSERT_DT datetime NULL COMMENT '등록일시',            
	UPDATE_USER_ID varchar(10) NULL COMMENT '수정자ID',              
	UPDATE_DT datetime NULL COMMENT '수정일시'
) 
COMMENT = '공급사 B2C 이력';

CREATE TABLE B2C_BAT_BEST_GOODS (
	CUST_CATE_CD varchar(20) NOT NULL COMMENT '구매사_카테고리_CD',
	VENDOR_ID varchar(20) NOT NULL COMMENT '공급사ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	RANK_NO int NOT NULL COMMENT '랭킹',
	REGI_DATE_TIME datetime NOT NULL COMMENT '집계일',
	PRIMARY KEY (CUST_CATE_CD, VENDOR_ID, GOOD_IDEN_NO)
) 
COMMENT = 'B2C_BEST상품';

CREATE TABLE B2C_BAT_POPULAR_GOODS (
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(20) NOT NULL COMMENT '공급사ID',
	RANK_NO int NOT NULL COMMENT '랭킹',
	REGI_DATE_TIME datetime NOT NULL COMMENT '집계일',
	PRIMARY KEY (GOOD_IDEN_NO, VENDOR_ID)
) 
COMMENT = 'B2C_인기상품';


