CREATE TABLE BAT_BEST_GOODS (
	CUST_CATE_CD varchar(20) NOT NULL COMMENT '구매사 카테고리 CD',
	WORK_ID int NOT NULL COMMENT '사업유형ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	RANK_NO int NOT NULL COMMENT '랭킹',
	INSERT_DT datetime NOT NULL COMMENT '집계일',
	PRIMARY KEY (CUST_CATE_CD, WORK_ID, GOOD_IDEN_NO)
)
COMMENT ='BEST 상품';

CREATE TABLE BAT_POPULAR_GOODS (
	WORK_ID int NOT NULL COMMENT '사업유형ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	RANK_NO int NOT NULL COMMENT '랭킹',
	INSERT_DT datetime NOT NULL COMMENT '집계일',
	PRIMARY KEY (WORK_ID, GOOD_IDEN_NO)
)
COMMENT ='인기상품';

CREATE TABLE BAT_ORDER_GOODS_TOTAL (
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	WORK_ID int NOT NULL COMMENT '사업유형ID',
	CUST_CATE_CD varchar(20) NOT NULL COMMENT '구매사_카테고리_CD',
	VENDOR_ID varchar(20) NOT NULL COMMENT '공급사ID',
	INSERT_DT datetime NOT NULL COMMENT '집계일',
	ORDE_QUAN decimal(7,0) NOT NULL COMMENT '주문수량',
	PRIMARY KEY (GOOD_IDEN_NO, WORK_ID, CUST_CATE_CD, VENDOR_ID)
)
COMMENT ='최근 3개월 상품집계';

CREATE TABLE BAT_ADM_MAIN (
	INFO_YMD varchar(8) NOT NULL COMMENT '일자_YYYYMMDD',
	INFO_TP varchar(10) NOT NULL COMMENT '정보TYPE',
	INSERT_DT datetime NULL COMMENT '생성일시',
	INFO_01 varchar(20) NULL COMMENT 'INFO_01',
	INFO_02 varchar(20) NULL COMMENT 'INFO_02',
	INFO_03 varchar(20) NULL COMMENT 'INFO_03',
	INFO_04 varchar(20) NULL COMMENT 'INFO_04',
	INFO_05 varchar(20) NULL COMMENT 'INFO_05',
	INFO_06 varchar(20) NULL COMMENT 'INFO_06',
	INFO_07 varchar(20) NULL COMMENT 'INFO_07',
	INFO_08 varchar(20) NULL COMMENT 'INFO_08',
	INFO_09 varchar(20) NULL COMMENT 'INFO_09',
	INFO_10 varchar(20) NULL COMMENT 'INFO_10',
	INFO_11 varchar(20) NULL COMMENT 'INFO_11',
	INFO_12 varchar(20) NULL COMMENT 'INFO_12',
	PRIMARY KEY (INFO_YMD, INFO_TP)
)
COMMENT ='운영사 메인정보';

CREATE TABLE BAT_VEN_MAIN (
	INFO_YMD varchar(8) NOT NULL COMMENT '일자_YYYYMMDD',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	INFO_TP varchar(10) NOT NULL COMMENT '정보TYPE',
	INSERT_DT datetime NULL COMMENT '생성일시',
	INFO_01 varchar(20) NULL COMMENT 'INFO_01',
	INFO_02 varchar(20) NULL COMMENT 'INFO_02',
	INFO_03 varchar(20) NULL COMMENT 'INFO_03',
	INFO_04 varchar(20) NULL COMMENT 'INFO_04',
	INFO_05 varchar(20) NULL COMMENT 'INFO_05',
	INFO_06 varchar(20) NULL COMMENT 'INFO_06',
	INFO_07 varchar(20) NULL COMMENT 'INFO_07',
	INFO_08 varchar(20) NULL COMMENT 'INFO_08',
	INFO_09 varchar(20) NULL COMMENT 'INFO_09',
	INFO_10 varchar(20) NULL COMMENT 'INFO_10',
	INFO_11 varchar(20) NULL COMMENT 'INFO_11',
	INFO_12 varchar(20) NULL COMMENT 'INFO_12',
	INFO_13 varchar(20) NULL COMMENT 'INFO_13',
	INFO_14 varchar(20) NULL COMMENT 'INFO_14',
	INFO_15 varchar(20) NULL COMMENT 'INFO_15',
	PRIMARY KEY (INFO_YMD, VENDOR_ID)
)
COMMENT ='공급사 메인정보';

