CREATE TABLE EST_BID (
	BID_ID int NOT NULL COMMENT '견적ID',
	BID_NM varchar(500) NULL COMMENT '견적명',
	BID_ST_CD varchar(10) NOT NULL DEFAULT '0' COMMENT '견적상태 (BIDSTATE)',
	BID_GOODS_NM varchar(100) NULL COMMENT '견적품목명',
	BID_START_DT DATETIME NULL COMMENT '견적시작일시',
	BID_END_DT datetime NULL COMMENT '견적종료일시',
	BID_GOODS_SPEC varchar(500) NULL COMMENT '견적품목규격',
	HOPE_AMT decimal(15,2) NULL COMMENT '희망가격',
	CHECK_NOTE text NULL COMMENT '확인사항',
	ATTACH_SEQ1 varchar(10) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 varchar(10) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 varchar(10) NULL COMMENT '첨부파일3',
	IS_BID_CERT varchar(10) NOT NULL DEFAULT '1' COMMENT '투찰시공인인증사용여부',
	NEW_GOODS_REQ_ID int NULL COMMENT '신규상품조회요청ID',
	GOOD_IDEN_NO varchar(20) NULL COMMENT '상품코드',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자',
	INSERT_DT datetime NULL COMMENT '등록일자',
	BID_STOP_YN varchar(1) NOT NULL DEFAULT 'N' COMMENT '견적중지YN',
	BID_STOP_REASON varchar(500) NULL COMMENT '견적중지사유',
	BID_STOP_USER_ID varchar(10) NULL COMMENT '견적중지처리자',
	BID_STOP_DT datetime NULL COMMENT '견적중지일자',
	BID_FORM_TP varchar(2) NOT NULL DEFAULT '10' COMMENT '견적형태',
	IS_LINK varchar(1) NOT NULL DEFAULT '1' COMMENT '연동제여부',
	PRIMARY KEY (BID_ID)                                               
)
COMMENT = '견적공고';

CREATE TABLE EST_BID_HIST (
	BID_HIST_ID int NOT NULL COMMENT '견적공고이력id',
	BID_ID int NULL COMMENT '견적ID',
	BID_NM varchar(500) NULL COMMENT '견적명',
	BID_ST_CD varchar(10) NULL COMMENT '견적상태',
	BID_GOODS_NM varchar(100) NULL COMMENT '견적품목명',
	BID_START_DT DATETIME NULL COMMENT '견적시작일시',
	BID_END_DT datetime NULL COMMENT '견적종료일자',
	BID_GOODS_SPEC varchar(500) NULL COMMENT '견적품목규격',
	HOPE_AMT decimal(15,2) NULL COMMENT '희망가격',
	CHECK_NOTE text NULL COMMENT '확인사항',
	ATTACH_SEQ1 varchar(10) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 varchar(10) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 varchar(10) NULL COMMENT '첨부파일3',
	IS_BID_CERT varchar(10) NULL COMMENT '투찰시공인인증사용',
	NEW_GOODS_REQ_ID VARCHAR(10) NULL COMMENT '신규상품조회요청ID',
	GOOD_IDEN_NO varchar(20) NULL COMMENT '상품코드',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자',
	INSERT_DT datetime NULL COMMENT '등록일자',
	BID_STOP_YN varCHAR(1) NULL COMMENT '견적중지YN',
	BID_STOP_REASON VARCHAR(500) NULL COMMENT '견적중지사유',
	BID_STOP_USER_ID VARCHAR(10) NULL COMMENT '견적중지처리자',
	BID_STOP_DT DATETIME NULL COMMENT '견적중지일자',
	BID_FORM_TP varchar(2) NULL COMMENT '견적형태',
	IS_LINK varchar(1) NULL COMMENT '연동제여부',
	PRIMARY KEY (BID_HIST_ID)                                               
)
COMMENT = '견적이력';

CREATE TABLE EST_BID_VENDOR (
	BID_ID int NOT NULL COMMENT '견적ID',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	VENDOR_BID_ST_CD varchar(10) NOT NULL DEFAULT '10' COMMENT '투찰,낙찰상태 (BID_VEN_STSTE)',
	GOODS_NM varchar(100) NULL COMMENT '상품명',
	GOODS_STND_SPEC varchar(200) NULL COMMENT '표준규격',
	GOODS_SPEC varchar(200) NULL COMMENT '대표규격',
	ORDER_UNIT varchar(10) NULL COMMENT '주문단위',
	BID_PRICE decimal(15,2) NULL COMMENT '투찰금액',
	STND_DELI_DAY decimal(2,0) NULL COMMENT '표준납기일',
	MINI_ORD_QUAN decimal(10,0) NULL COMMENT '최소주문수량',
	MAKE_COMP_NM varchar(100) NULL COMMENT '제조사',
	GOODS_DESC text NULL COMMENT '상품상세설명',
	ATTACH_SEQ1 varchar(10) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 varchar(10) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 varchar(10) NULL COMMENT '첨부파일3',
	ATTACH_SEQ4 varchar(10) NULL COMMENT '첨부파일4',       	
	ATTACH_SEQ5 varchar(10) NULL COMMENT '첨부파일5',
	IS_GOODS_REG varchar(1) NOT NULL DEFAULT '0' COMMENT '상품등록여부',
	VENDOR_BID_DT datetime NULL COMMENT '투찰일시',      	
	VENDOR_BID_USER_ID varchar(10) NULL COMMENT '투찰자',    	
	CHECK_DT datetime NULL COMMENT '확인일자',
	CHECK_USER_ID varchar(10) NULL COMMENT '확인자id',       	
	VENDOR_BID_RESULT_CD varchar(10) NOT NULL DEFAULT '0' COMMENT '견적결과 (BID_RESULT)',          	
	DIST_RATE decimal(8,0) NULL COMMENT '배분율',
	NEGO_FL varchar(1) DEFAULT '0' NULL COMMENT '수의사담',	
	LINK_SELECT varchar(1) NULL COMMENT '연동제선택',    	
	PRIMARY KEY (BID_ID, VENDOR_ID)                                          
)      
COMMENT = '견적 공급사 정보';

CREATE TABLE EST_BID_VENDOR_HIST (
	BID_VENDOR_HIST_ID int NOT NULL COMMENT '견적 공급사 이력ID',
	BID_ID int NULL COMMENT '공급사ID',
	VENDOR_ID varchar(10) NULL COMMENT '견적ID',
	VENDOR_BID_ST_CD varchar(10) NULL COMMENT '투찰,낙찰상태 (BID_VEN_STSTE)',    
	GOODS_NM varchar(100) NULL COMMENT '상품명',
	GOODS_STND_SPEC varchar(200) NULL COMMENT '표준규격',      
	GOODS_SPEC varchar(200) NULL COMMENT '대표규격',
	ORDER_UNIT varchar(10) NULL COMMENT '주문단위',
	BID_PRICE decimal(15,2) NULL COMMENT '투찰금액',   
	STND_DELI_DAY decimal(2,0) NULL COMMENT '표준납기일',   
	MINI_ORD_QUAN decimal(10,0) NULL COMMENT '최소주문수량',      
	MAKE_COMP_NM varchar(100) NULL COMMENT '제조사',
	GOODS_DESC text NULL COMMENT '상품상세설명',
	ATTACH_SEQ1 varchar(10) NULL COMMENT '첨부파일1',  
	ATTACH_SEQ2 varchar(10) NULL COMMENT '첨부파일2',   
	ATTACH_SEQ3 varchar(10) NULL COMMENT '첨부파일3', 
	ATTACH_SEQ4 varchar(10) NULL COMMENT '첨부파일4',       	
	ATTACH_SEQ5 varchar(10) NULL COMMENT '첨부파일5',      	
	IS_GOODS_REG varchar(1) NULL COMMENT '상품등록여부',         	    
	VENDOR_BID_DT datetime NULL COMMENT '투찰일시',  	
	VENDOR_BID_USER_ID varchar(10) NULL COMMENT '투찰자', 	
	CHECK_DT datetime NULL COMMENT '확인일자',
	CHECK_USER_ID varchar(10) NULL COMMENT '확인자id',	
	VENDOR_BID_RESULT_CD varchar(10) NULL COMMENT '견적결과 (BID_RESULT)',
	DIST_RATE decimal(2,0) NULL COMMENT '배분율',
	NEGO_FL varchar(1) NULL COMMENT '수의시담',
	LINK_SELECT varchar(1) NULL COMMENT '연동제선택',      	
	PRIMARY KEY (BID_VENDOR_HIST_ID)
)
COMMENT = '견적 공급사 정보 이력';

CREATE TABLE EST_NEW_GOODS_REQ (
	NEW_GOODS_REQ_ID int NOT NULL COMMENT '신규상품조회요청ID',
	REQ_GOODS_NM varchar(100) NULL COMMENT '요청품목명',
	REQ_GOODS_SPEC varchar(500) NULL COMMENT '요청규격',
	REQ_NOTE text NULL COMMENT '요청사항',
	NEW_GOODS_ST_CD varchar(10) NOT NULL DEFAULT '10' COMMENT '신규품목요청상태 (NEW_PROD_STATE)',
	INSERT_USER_ID varchar(10) NULL COMMENT '요청자',
	INSERT_BORG_ID varchar(10) NULL COMMENT '요청자조직',
	INSERT_DT datetime NULL COMMENT '요청일자',
	RECEIVE_USER_ID varchar(10) NULL COMMENT '처리자',
	RECEIVE_DT datetime NULL COMMENT '처리일자',
	GOOD_IDEN_NO varchar(20) NULL COMMENT '상품코드',
	ATTACH_SEQ1 varchar(10) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 varchar(10) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 varchar(10) NULL COMMENT '첨부파일3',
	ATTACH_SEQ4 varchar(10) NULL COMMENT '첨부파일4',
	ATTACH_SEQ5 varchar(10) NULL COMMENT '첨부파일5',
	IS_DELETE varchar(1) NOT NULL DEFAULT 0 COMMENT '삭제여부',           
	ACTION_NOTE text NULL COMMENT '조치내용',           
	REQ_GOOD_IDEN_NO varchar(20) DEFAULT NULL NULL COMMENT '요청옵션대표상품코드',  
	REQ_REASON varchar(500) NULL COMMENT '요청사유',
	REQ_USER_NM varchar(100) NULL COMMENT '요청자명',   
	PRIMARY KEY (NEW_GOODS_REQ_ID)
)
COMMENT = '신규상품요청';

CREATE TABLE EST_NEW_GOODS_REQ_HIST (
	NEW_GOODS_REQ_HIST_ID int NOT NULL COMMENT '신규상품조회요청이력ID',
	NEW_GOODS_REQ_ID int NOT NULL COMMENT '신규상품조회요청ID',
	BID_GOODS_NM varchar(100) NULL COMMENT '요청품목명',
	BID_GOODS_SPEC varchar(500) NULL COMMENT '요청규격',
	REQ_NOTE text NULL COMMENT '요청사항',
	NEW_GOODS_ST_CD varchar(10) NULL COMMENT '신규품목요청상태 (NEW_PROD_STATE)',
	INSERT_USER_ID varchar(10) NULL COMMENT '요청자',
	INSERT_BORG_ID varchar(10) NULL COMMENT '요청자조직',
	INSERT_DT datetime NULL COMMENT '요청일자',
	RECEIVE_USER_ID varchar(10) NULL COMMENT '처리자',
	RECEIVE_DT datetime NULL COMMENT '처리일자',
	GOOD_IDEN_NO varchar(20) NULL COMMENT '상품코드',
	ATTACH_SEQ1 VARCHAR(10) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 VARCHAR(10) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 VARCHAR(10) NULL COMMENT '첨부파일3',
	ATTACH_SEQ4 VARCHAR(10) NULL COMMENT '첨부파일4',
	ATTACH_SEQ5 VARCHAR(10) NULL COMMENT '첨부파일5',
	IS_DELETE varchar(1) NULL COMMENT '삭제여부',
	ACTION_NOTE text NULL COMMENT '조치내용',
	REQ_GOOD_IDEN_NO varchar(20) DEFAULT NULL NULL COMMENT '요청옵션대표상품코드', 
	REQ_REASON varchar(500) NULL COMMENT '요청사유',
	REQ_USER_NM varchar(100) NULL COMMENT '요청자명',
	PRIMARY KEY (NEW_GOODS_REQ_HIST_ID)                                                       
)
COMMENT = '신규상품요청 이력';

