CREATE TABLE ETC_ATTACH (
	ATTACH_SEQ int NOT NULL COMMENT '첨부파일SEQ',
	ATTACH_FILE_NM varchar(200) NULL COMMENT '첨부파일명',
	ATTACH_FILE_PATH varchar(400) NULL COMMENT '첨부파일경로',
	INSERT_DT datetime NULL COMMENT '등록일자',
	PRIMARY KEY (ATTACH_SEQ)
)
COMMENT = '첨부파일 관리';

CREATE TABLE ETC_AUTH_CERT (
	BORG_ID varchar(10) NOT NULL COMMENT '조직ID',
	USER_DN varchar(200) NULL COMMENT '사용자DN',
	INSERT_DT datetime NULL COMMENT '등록일자',
	INSERT_USER_ID varchar(20) NULL COMMENT '생성자ID',
	PRIMARY KEY (BORG_ID)
)
COMMENT = '법인공인인증';

CREATE TABLE ETC_HOLIDAY_MNG (
	HOLIDAY varchar(10) NOT NULL COMMENT '휴일',
	HOLIDAY_NM varchar(50) NULL COMMENT '휴일명',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일시',
	PRIMARY KEY (HOLIDAY)
)
COMMENT = '휴일관리';

CREATE TABLE ETC_LOGIN_FAIL (
	LOGIN_ID varchar(30) NULL COMMENT '로그인ID',
	LOGIN_IP varchar(20) NULL COMMENT '로그인IP',
	INSERT_DT datetime NULL COMMENT '생성 일자'
)
COMMENT = '로그인 실패 LOG';

CREATE TABLE ETC_MAIL (
	MAIL_ID varchar(10) NOT NULL COMMENT '메일SEQ',
	MAIL_TITLE varchar(150) NULL COMMENT '메일제목',
	MAIL_CONTENTS text NULL COMMENT '메일내용',
	RECEIVE_ADDRS TEXT NULL COMMENT '수신자메일주소_[;로구분]',
	SEND_FL varchar(10) NOT NULL DEFAULT '0' COMMENT '발송FLAG',
	ERR_MSG varchar(1000) NULL COMMENT '에러메시지',
	SEND_DT datetime NULL COMMENT '발송일자',
	INSERT_DT datetime NULL COMMENT '생성일자',
	PRIMARY KEY (MAIL_ID)
)
COMMENT = '메일관리';


CREATE TABLE ETC_MSG_TEMPLATE (
	TEMPLATE_CD varchar(20) NOT NULL COMMENT '템플릿코드',
	SEND_TP varchar(20) NOT NULL DEFAULT 'KKO' COMMENT '전송수단',
	SEND_SVC varchar(20) NOT NULL DEFAULT 'BITMP' COMMENT '전송서비스',
	TITLE varchar(100) NULL COMMENT '제목',
	CONTENTS varchar(4000) NULL COMMENT '내용',
	TEMP_DESC varchar(4000) NULL COMMENT '설명',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자ID',
	INSERT_DATE datetime NULL COMMENT '등록일',
	UPDATE_USER_ID varchar(20) NULL COMMENT '수정자ID',
	UPDATE_DATE datetime NULL COMMENT '수정일시',
	PRIMARY KEY (TEMPLATE_CD)
)
COMMENT = '문자 템플릿 관리';
