CREATE TABLE GDS_ADD_GOODS (
	ADD_GOODS_ID bigint NOT NULL COMMENT '추가구성상품ID',
	GOOD_IDEN_NO varchar(20) NULL COMMENT '상품코드',
	ADD_GOOD_IDEN_NO varchar(20) NULL COMMENT '추가구성상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
    PRIMARY KEY (ADD_GOODS_ID)
)
COMMENT='추가구성상품';

-- CREATE TABLE GDS_AUTO_RATE_INFO (
-- 	MTRL_CD varchar(20) NOT NULL COMMENT '통계품목코드',
-- 	STA_DT datetime NULL COMMENT '시작일자',
-- 	RATIO1 int NULL COMMENT '비율1',
-- 	BP1 varchar(10) NULL COMMENT 'BP1',
-- 	RATIO2 int NULL COMMENT '비율2',
-- 	BP2 varchar(10) NULL COMMENT 'BP2',
-- 	RATIO3 int NULL COMMENT '비율3',
-- 	BP3 varchar(10) NULL COMMENT 'BP3',
-- 	RATIO4 int NULL COMMENT '비율4',
-- 	BP4 varchar(10) NULL COMMENT 'BP4',
-- 	RATIO5 int NULL COMMENT '비율5',
-- 	BP5 varchar(10) NULL COMMENT 'BP5',
-- 	RATIO6 int NULL COMMENT '비율6',
-- 	BP6 varchar(10) NULL COMMENT 'BP6',
-- 	RATIO7 int NULL COMMENT '비율7',
-- 	BP7 varchar(10) NULL COMMENT 'BP7',
--     PRIMARY KEY (MTRL_CD)
-- )
-- COMMENT='자동물량배분정보';
CREATE TABLE GDS_BAT_GOODS_MAST (
	BAT_MAST_ID int NOT NULL COMMENT '마스터ID',
	BAT_ST varchar(1) DEFAULT '0'NOT NULL COMMENT '상태',
	BAT_MAST_NM varchar(100) NOT NULL COMMENT '일괄등록명',
	BAT_DT datetime NOT NULL COMMENT '적용일시',
	INSERT_USER_ID varchar(20) NOT NULL COMMENT '등록자ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	TRANS_DT datetime NULL COMMENT '처리일시',
	PRIMARY KEY (BAT_MAST_ID)
)
COMMENT='일괄등록상품마스터';

CREATE TABLE GDS_BAT_GOODS (
	BAT_TRANS_ID int NOT NULL COMMENT '처리ID',
	BAT_MAST_ID int NOT NULL COMMENT '마스터ID',
	INS_UPD_FL varchar(10) NULL COMMENT '등록수정플래그',
	ERR_CONT varchar(200) NULL COMMENT '미적용 내용',
	GOOD_IDEN_NO varchar(20) NULL COMMENT '상품코드',
	CATE_CD varchar(10) NULL COMMENT '카테고리코드',
	GOODS_NM varchar(200) NULL COMMENT '상품명',
	GOODS_REG_YEAR varchar(4) NULL COMMENT '상품실적년',
	GOODS_SPEC varchar(500) NULL COMMENT '규격',
	MTRL_CD varchar(20) NULL COMMENT '품종코드',
	MTRL_DETL_CD varchar(20) NULL COMMENT '세부품종코드',
	TAX_CD varchar(10) not null default '10' COMMENT '과세구분 (VTAXTYPECODE)',
	GOODS_MNG_USER_NM varchar(100) NULL COMMENT '상품담당자',
	ORDER_UNIT varchar(10) NULL COMMENT '주문단위',
	LOGI_YN varchar(1) not null default 'N' COMMENT '물류_YN',
	LOGI_CHECK_YN varchar(1) not null default 'N' COMMENT '물류_품질검사여부_YN',
	GOODS_TP varchar(10) not null default '10' COMMENT '상품구분 (ORDERGOODSTYPE)',
	VENDOR_EXPOSE_YN varchar(1) not null default 'N' COMMENT '공급사노출YN',
	DIST_FL varchar(10) not null default '0' COMMENT '물량배분플래그',
	ADD_GOODS_YN varchar(1) not null default 'N' COMMENT '추가구성YN',
	ADM_IMG_MNG_YN varchar(1) not null default 'N' COMMENT '운영사_이미지관리YN',
	VENDOR_CD varchar(10) NULL COMMENT '공급사코드',
	USE_ST varchar(1) NULL COMMENT '사용상태',
	SELL_PRICE decimal(15,2) NULL COMMENT '판매가',
	BUY_PRICE decimal(15,2) NULL COMMENT '매입가',
	MINI_ORD_QUAN decimal(10,2) NULL COMMENT '최소주문수량',
	DELI_LEAD_DAY decimal(2,0) NULL COMMENT '납품소요일',
	DIST_RATE int NULL COMMENT '물량배분율',
	MAKE_COMP_NM varchar(100) NULL COMMENT '제조사',
	VENDOR_STOCK_YN char(1) not null default 'N' COMMENT '공급사 재고관리여부',
	VENDOR_STOCK_CNT decimal(15,2) not null default '0' COMMENT '재고수량',
	UPD_REASON varchar(200) null COMMENT '변경사유',
	PRIMARY KEY (BAT_TRANS_ID)                 
)
COMMENT='일괄등록상품';

CREATE TABLE GDS_CATE_MAST (
	CATE_ID int NOT NULL COMMENT '표준카테고리ID',
	CATE_NM varchar(200) NULL COMMENT '카테고리명',
	CATE_CD varchar(10) NULL COMMENT '카테고리CD',
	CATE_DESC varchar(200) NULL COMMENT '카테고리 설명',
	PAR_CATE_ID int NULL COMMENT '상위카테고리SEQ',
	CATE_LEVEL varchar(2) NULL COMMENT '카테고리 레벨',
	DISP_NO varchar(2) NULL COMMENT '진열순서',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일',
	UPDATE_USER_ID varchar(10) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일',
	PRIMARY KEY (CATE_ID)
)
COMMENT='표준카테고리';

CREATE TABLE GDS_CUST_CATE_MAST (
	CUST_CATE_MAST_CD varchar(3) NOT NULL COMMENT '구매사_카테고리_마스터CD',
	CUST_CATE_MAST_NM varchar(100) NOT NULL COMMENT '카테고리_마스터명',
	USE_YN varchar(1) NOT null default 'Y' COMMENT '사용여부_YN',
	DISP_NO int NULL COMMENT '순서',
	CUST_CATE_MAST_DESC varchar(500) NULL COMMENT '마스터_설명',
	INSERT_USER_ID varchar(20) NOT NULL COMMENT '등록자ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	UPDATE_USER_ID varchar(20) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (CUST_CATE_MAST_CD)
)
COMMENT='구매사 카테고리 마스터';

CREATE TABLE GDS_CUST_CATE (
	CUST_CATE_CD varchar(20) NOT NULL COMMENT '구매사_카테고리_CD',
	CUST_CATE_MAST_CD varchar(3) NOT NULL COMMENT '구매사_카테고리_마스터CD',
	PAR_CUST_CATE_CD varchar(20) NULL COMMENT '상위_카테고리_CD',
	CUST_CATE_NM varchar(100) NOT NULL COMMENT '카테고리명',
	CATE_LEVEL int NOT NULL COMMENT '카테고리_레벨',
	USE_YN varchar(1) NOT null default 'Y' COMMENT '사용여부_YN',
	B2C_BEST_YN varchar(1) DEFAULT 'Y' NOT NULL COMMENT 'B2C_메인베스트_YN',
	DISP_NO int NULL COMMENT '순서',
	CUST_CATE_DESC varchar(500) NULL COMMENT '카테고리_설명',
	INSERT_USER_ID varchar(20) NOT NULL COMMENT '등록자ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	UPDATE_USER_ID varchar(20) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (CUST_CATE_CD)
)
COMMENT='구매사_카테고리';

CREATE TABLE GDS_CUST_CATE_CONN (
	CUST_CATE_CD varchar(20) NOT NULL COMMENT '구매사_카테고리_CD',
	CATE_ID int NOT NULL COMMENT '표준카테고리SEQ',
	INSERT_USER_ID varchar(20) NOT NULL COMMENT '등록자ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	PRIMARY KEY (CUST_CATE_CD, CATE_ID)
)
COMMENT='구매사 카테고리 연결';

CREATE TABLE GDS_CUST_CATE_CONN_HIST (
	HIST_ID int NOT NULL COMMENT 'HIST_ID',
	CUST_CATE_CD varchar(20) NOT NULL COMMENT '구매사_카테고리_CD',
	CATE_ID int NOT NULL COMMENT '표준카테고리SEQ',
	INSERT_USER_ID varchar(20) NOT NULL COMMENT '등록자ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	PRIMARY KEY (HIST_ID)
)
COMMENT='구매사 카테고리 연결 HIST';

CREATE TABLE GDS_GOODS (
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	CATE_ID int NULL COMMENT '표준카테고리SEQ',
	GOODS_NM varchar(200) NULL COMMENT '상품명',
	TAX_CD varchar(10) not null default '10' COMMENT '과세구분 (VTAXTYPECODE)',
	DIST_FL varchar(10) not null default '0' COMMENT '물량배분플래그',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자',
	INSERT_DT datetime NULL COMMENT '등록일자',
	GOODS_MNG_USER_ID varchar(10) NULL COMMENT '상품담당자ID',
	OPT_GB_FL varchar(1) not null default 'N' COMMENT '옵션구분FLAG',
	GOODS_REG_YEAR varchar(4) NULL COMMENT '상품실적년',
	GOODS_SPEC varchar(300) NULL COMMENT '상품규격',
	ORDER_UNIT varchar(10) NULL COMMENT '주문단위',
	GOODS_TP varchar(10) NOT null default '10' COMMENT '상품구분 (ORDERGOODSTYPE)',
	VENDOR_EXPOSE_YN varchar(10) not null default 'Y' COMMENT '공급사노출YN',
	ADD_GOODS_MAST_YN varchar(1) not null default 'N' COMMENT '추가구성마스터YN',
	ADD_GOODS_DESC varchar(200) NULL COMMENT '추가구성설명',
	ADM_IMG_MNG_YN varchar(1) not null default 'N' COMMENT '운영사_이미지관리YN',
	GOODS_IMG_PATH1 varchar(500) NULL COMMENT '상품이미지1',
	GOODS_IMG_PATH2 varchar(500) NULL COMMENT '상품이미지2',
	GOODS_IMG_PATH3 varchar(500) NULL COMMENT '상품이미지3',
	GOODS_IMG_PATH4 varchar(500) NULL COMMENT '상품이미지4',
	GOODS_IMG_PATH5 varchar(500) NULL COMMENT '상품이미지5',
	GOODS_DESC TEXT NULL COMMENT '상품설명',
	REPRE_GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '대표상품코드',
	REPRE_DISP_NO INT NULL COMMENT '대표상품출력순서',
	OPT_COST_CODE INT not null default '0' COMMENT '옵션단가코드', 
	LOGI_YN varchar(1) DEFAULT 'N' not NULL COMMENT '물류_YN',
	LOGI_STOCK_PRICE decimal(15,2) NULL COMMENT '물류_재고판매가',
	LOGI_CHECK_YN varchar(1) DEFAULT 'Y' NOT NULL COMMENT '물류_품질검사여부_YN',
	PACKAGE_QUAN int DEFAULT 1 NULL COMMENT '낱개수량',
	GOOD_TEXT_DESC TEXT NULL COMMENT '특이사항',
	OPT_DISP_NO INT NULL COMMENT '옵션코드순서',
	PRIMARY KEY (GOOD_IDEN_NO)
)
COMMENT='상품마스터';

CREATE TABLE GDS_GOODS_HIST (
	GOODS_HIST_ID int NOT NULL COMMENT '상품히스토리',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	CATE_ID varchar(10) NULL COMMENT '표준카테고리SEQ',
	GOODS_NM varchar(100) NULL COMMENT '상품명',
	TAX_CD varchar(10) not null default '10' COMMENT '과세구분 (VTAXTYPECODE)',
	DIST_FL varchar(10) NULL COMMENT '물량배분플래그',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자',
	INSERT_DT datetime NULL COMMENT '등록일자',
	GOODS_MNG_USER_ID varchar(10) NULL COMMENT '상품담당자ID',
	OPT_GB_FL varchar(1) NULL COMMENT '옵션구분FLAG',
	GOODS_REG_YEAR varchar(4) NULL COMMENT '상품실적년',
	GOODS_SPEC varchar(300) NULL COMMENT '상품규격',
	ORDER_UNIT varchar(10) NULL COMMENT '주문단위',
	GOODS_TP_CD varchar(10) NULL COMMENT '상품구분 (ORDERGOODSTYPE)',
	VENDOR_EXPOSE_YN varchar(10) NULL COMMENT '공급사노출YN',
	ADD_GOODS_MAST_YN varchar(1) NULL COMMENT '추가구성마스터YN',
	ADD_GOODS_DESC varchar(200) NULL COMMENT '추가구성설명',
	ADM_IMG_MNG_YN varchar(1) NULL COMMENT '운영사_이미지관리YN',
	GOODS_IMG_PATH1 varchar(500) NULL COMMENT '상품이미지1',
    GOODS_IMG_PATH2 varchar(500) NULL COMMENT '상품이미지2',
	GOODS_IMG_PATH3 varchar(500) NULL COMMENT '상품이미지3',
	GOODS_IMG_PATH4 varchar(500) NULL COMMENT '상품이미지4',
	GOODS_IMG_PATH5 varchar(500) NULL COMMENT '상품이미지5',
	GOODS_DESC TEXT NULL COMMENT '운영사상품설명',
	REPRE_GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '대표상품코드',
	REPRE_DISP_NO int NULL COMMENT '대표상품출력순서',
	OPT_COST_CODE INT null COMMENT '옵션단가코드',
	ADD_GOODS_ID_ARR varchar(200) NULL COMMENT '추가상품ID_[,]로구분',
	HIST_INSERT_BORG_ID varchar(10) NULL COMMENT '이력업체ID',
	HIST_INSERT_USER_ID varchar(10) NULL COMMENT '이력등록자ID',
	HIST_INSERT_DT datetime NULL COMMENT '이력등록일시',
	LOGI_YN varchar(1) DEFAULT 'N' NULL COMMENT '물류_YN',
	LOGI_STOCK_PRICE decimal(15,2) NULL COMMENT '물류_재고판매가',
	LOGI_CHECK_YN varchar(1) DEFAULT 'Y' NULL COMMENT '물류_품질검사여부_YN',
	PACKAGE_QUAN int NULL COMMENT '낱개수량',
	GOOD_TEXT_DESC TEXT NULL COMMENT '특이사항',
	OPT_DISP_NO INT null COMMENT '옵션코드순서',
	PRIMARY KEY (GOODS_HIST_ID)
)
COMMENT='상품마스터 이력';

CREATE TABLE GDS_GOODS_MEMO (
	GOODS_MEMO_ID int NOT NULL COMMENT '상품메모ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	MEMO varchar(2000) NOT NULL COMMENT '메모',
	ATTACH_SEQ int NULL COMMENT '첨부파일',
	INSERT_USER_ID varchar(20) NOT NULL COMMENT '등록자',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	UPDATE_USER_ID varchar(20) NULL COMMENT '수정자',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	PRIMARY KEY (GOODS_MEMO_ID)
)
COMMENT='상품 메모';

CREATE TABLE GDS_GOODS_APP (
	GOODS_APP_ID bigint NOT NULL COMMENT '상품가격변경승인ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	APP_ST varchar(2) not null default '10' COMMENT '승인상태',
	REQ_USER_ID varchar(10) NULL COMMENT '요청자ID',
	REQ_DT datetime NULL COMMENT '요청일자',
	APP_USER_ID varchar(10) NULL COMMENT '처리자ID',
	APP_DT datetime NULL COMMENT '처리일자',
	RETURN_DESC varchar(2000) NULL COMMENT '반려사유',
	ORG_BUY_PRICE decimal(15,2) NULL COMMENT '기존매입단가',
	ORG_SELL_PRICE decimal(15,2) NULL COMMENT '기존판매단가',
	CHG_KIND varchar(3) NULL COMMENT '변경구분_ADM/VEN',
	CHG_DESC varchar(2000) NULL COMMENT '변경사유',
	PRIMARY KEY (GOODS_APP_ID)
)
COMMENT='상품가격변경승인';

CREATE TABLE GDS_GOODS_COMMON_OPTION (
	GOODS_COMM_OPT_ID bigint NOT NULL COMMENT '상품공통옵션ID',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	OPTION_TP varchar(10) NULL COMMENT '옵션구분',
	OPTION_NM varchar(100) NULL COMMENT '옵션명',
	OPTION_VALUE varchar(500) NULL COMMENT '옵션값',
	INSERT_DT datetime NULL COMMENT '등록일',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자',
	PRIMARY KEY (GOODS_COMM_OPT_ID)
)
COMMENT='상품공통옵션';

CREATE TABLE GDS_GOODS_DISPLAY (
	GOODS_DISP_ID bigint NOT NULL COMMENT '상품진열ID',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	DISP_TP varchar(10) NULL COMMENT '진열구분',
	DISP_TP_CD varchar(10) NULL COMMENT '진열구분코드',
	INSERT_DT datetime NULL COMMENT '등록일',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자',
	USE_YN varchar(1) DEFAULT 'Y' NOT NULL COMMENT '진열여부',
	PRIMARY KEY (GOODS_DISP_ID)
)
COMMENT='상품진열';

CREATE TABLE GDS_GOODS_DISPLAY_HIST (
	GOOD_HIST_ID int NOT NULL COMMENT '상품히스토리ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	AREA_ID_ARR varchar(1000) NULL COMMENT '권역ID_[,]로 구분',
	WORK_ID_ARR varchar(1000) NULL COMMENT '공사유형ID_[,]로 구분',
	BRANCH_ID_ARR varchar(1000) NULL COMMENT '사업장ID_[,]로 구분',
	HIST_INSERT_BORG_ID varchar(10) NULL COMMENT '이력업체ID',
	HIST_INSERT_USER_ID varchar(10) NULL COMMENT '이력등록자ID',
	HIST_INSERT_DT datetime NULL COMMENT '이력등록일시',
	USE_YN VARCHAR(1) NOT NULL COMMENT '진열여부',
	PRIMARY KEY (GOOD_HIST_ID)
)
COMMENT='상품진열이력';

CREATE TABLE GDS_GOODS_DISPLAY_BRANCH (
	GOODS_DISPLAY_BRANCH_ID bigint NOT NULL COMMENT '상품진열사업장ID',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '공급사ID',
	VENDOR_ID varchar(10) NULL COMMENT '상품코드',
	BRANCH_ID varchar(10) NULL COMMENT '사업장ID',
	INSERT_DT datetime NULL COMMENT '등록일',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자',
	USE_YN varchar(1) DEFAULT 'Y' NOT NULL COMMENT '진열여부',
	PRIMARY KEY (GOODS_DISPLAY_BRANCH_ID)
)
COMMENT='상품진열사업장';

CREATE TABLE GDS_GOODS_FIX (
	GOODS_FIX_ID int NOT NULL COMMENT '요청ID',
	GOOD_IDEN_NO varchar(20) NOT NULL COMMENT '공급사ID',
	VENDOR_ID varchar(10) NOT NULL COMMENT '상품코드',
	CHG_GB_CD varchar(10) not null default '20' COMMENT '변경구분 (APPLTFIXCODE)',
	CHG_BUY_PRICE decimal(15,2) NULL COMMENT '변경요청매입단가',
	REQ_REASON varchar(1000) NULL COMMENT '요청사유',
	TRANS_ST varchar(10) not null default '0' COMMENT '처리상태 (REQFIXAPPSTATE)',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일',
	APP_USER_ID varchar(10) NULL COMMENT '확인자ID',
	APP_DT datetime NULL COMMENT '확인일',
	CANCEL_REASON varchar(500) NULL COMMENT '반려사유',
	BEFORE_PRICE decimal(15,2) NULL COMMENT '이전단가',
	PRIMARY KEY (GOODS_FIX_ID)
)
COMMENT='공급사품목변경';

CREATE TABLE GDS_GOODS_REQUEST (
	GOODS_REQ_ID int NOT NULL COMMENT '상품등록요청SEQ',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사코드',
	GOODS_NM varchar(100) NULL COMMENT '상품명',
	BUY_PRICE decimal(15,2) NULL COMMENT '매입단가',
	DELI_LEAD_DAY decimal(2,0) NULL COMMENT '납품소요일수',
	MINI_ORD_QUAN decimal(10,0) NULL COMMENT '최소구매수량',
	MAKE_COMP_NM varchar(100) NULL COMMENT '제조사',
	GOODS_SAME_WORD varchar(500) NULL COMMENT '동의어',
	GOODS_IMG_PATH1 varchar(500) NULL COMMENT '상품이미지1',
	GOODS_IMG_PATH2 varchar(500) NULL COMMENT '상품이미지2',
	GOODS_IMG_PATH3 varchar(500) NULL COMMENT '상품이미지3',
	GOODS_IMG_PATH4 varchar(500) NULL COMMENT '상품이미지4',
	GOODS_IMG_PATH5 varchar(500) NULL COMMENT '상품이미지4',
	GOODS_DESC TEXT NULL COMMENT '상품설명',
	VENDOR_STOCK_CNT decimal(15,2) NULL COMMENT '재고수량',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일',
	APP_ST varchar(10) NOT null default '0' COMMENT '처리상태 (REQAPPSTATE)',
	CANCEL_REASON varchar(500) NULL COMMENT '반려사유',
	ADMIN_USER_ID varchar(10) NULL COMMENT '담당운영자ID',
	APP_USER_ID varchar(10) NULL COMMENT '확인자ID',
	APP_DT datetime NULL COMMENT '확인일',
	GOODS_REG_DT datetime NULL COMMENT '품목등록일',
	GOODS_MNG_USER_ID varchar(10) NULL COMMENT '상품담당자ID',
	ATTACH_SEQ1 varchar(50) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 varchar(50) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 varchar(100) NULL COMMENT '첨부파일3',
	GOOD_TEXT_DESC TEXT NULL COMMENT '상품 특이사항',
	B2C_DISP_YN varchar(1) null default 'N' COMMENT 'B2C_진열여부_Default:N',
	PRIMARY KEY (GOODS_REQ_ID)
)
COMMENT='상품등록요청';

CREATE TABLE GDS_GOODS_VENDOR (
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID VARCHAR(10) NOT NULL COMMENT '공급사ID',
	GOODS_REQ_ID INT NULL COMMENT '상품등록요청SEQ',
	DELI_LEAD_DAY DECIMAL(2,0) NULL COMMENT '납품소요일수',
	MINI_ORD_QUAN decimal(10,0) NULL COMMENT '최소주문수량',
	MAKE_COMP_NM varchar(100) NULL COMMENT '제조사',
	GOODS_IMG_PATH1 varchar(500) NULL COMMENT '상품이미지1',
	GOODS_IMG_PATH2 varchar(500) NULL COMMENT '상품이미지2',
	GOODS_IMG_PATH3 varchar(500) NULL COMMENT '상품이미지3',
	GOODS_IMG_PATH4 varchar(500) NULL COMMENT '상품이미지4',
	GOODS_IMG_PATH5 varchar(500) NULL COMMENT '상품이미지5',
	GOODS_SAME_WORD varchar(500) NULL COMMENT '동의어',
	GOODS_DESC TEXT NULL COMMENT '상품설명',
	VENDOR_STOCK_CNT decimal(15,2) NULL COMMENT '공급사재고수량_최근',
	INSERT_USER_ID VARCHAR(10) NULL COMMENT '등록자ID',
	INSERT_DT DATETIME NULL COMMENT '등록일시',
	UPDATE_USER_ID VARCHAR(10) NULL COMMENT '수정자ID',
	UPDATE_DT DATETIME NULL COMMENT '수정일시',
	ORDER_CNT INT NULL COMMENT '주문횟수',
	USE_ST VARCHAR(1) DEFAULT '1' NULL COMMENT '사용상태',
	DIST_RATE INT NULL COMMENT '물량배분율',
	VENDOR_DISP_NO INT DEFAULT 0 NOT NULL COMMENT '상품우선순위_진열순위',
	SELL_PRICE DECIMAL(15,2) NULL COMMENT '판매가_옵션기본',
	OPT_SELL_ADD_PRICE DECIMAL(15,2) NULL COMMENT '판매가_추가금액',
	BUY_PRICE DECIMAL(15,2) NULL COMMENT '매입가_옵션기본',
	OPT_BUY_ADD_PRICE DECIMAL(15,2) NULL COMMENT '매입가_추가금액',
	BUY_RATE DECIMAL(8, 2) NULL COMMENT '기준매익율',
	VENDOR_STOCK_YN CHAR(1) DEFAULT 'N' NULL COMMENT '공급사재고관리_YN',
	VENDOR_STOCK_SAVE_QUAN INT NULL COMMENT '공급사안전재고수',
	VENDOR_STOCK_SAVE_AUTO CHAR(1) DEFAULT '1' NULL COMMENT '공급사안전재고자동',
	VENDOR_STOCK_SORT INT DEFAULT 0 NULL COMMENT '공급사재고소팅',
	ORDER_BUNDLE_QUAN INT NULL COMMENT '주문묶음수량',
	ATTACH_SEQ1 VARCHAR(50) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 VARCHAR(50) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 VARCHAR(50) NULL COMMENT '첨부파일3',
	LOGI_ORDER_UNIT VARCHAR(10) NULL COMMENT '주문단위_물류',
	B2C_DISP_YN VARCHAR(1) DEFAULT 'N' NULL COMMENT 'B2C 진열여부_Default:N',
	PRIMARY KEY (GOOD_IDEN_NO, VENDOR_ID)
)
COMMENT='상품공급사';

CREATE TABLE GDS_GOODS_VENDOR_HIST (
	GOODS_HIST_ID INT not null COMMENT '히스토리ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID VARCHAR(10) NOT NULL COMMENT '공급사ID',
	GOODS_REQ_ID INT NULL COMMENT '상품등록요청SEQ',
	DELI_LEAD_DAY DECIMAL(2,0) NULL COMMENT '납품소요일수',
	MINI_ORD_QUAN decimal(10,0) NULL COMMENT '최소주문수량',
	MAKE_COMP_NM varchar(100) NULL COMMENT '제조사',
	GOODS_IMG_PATH1 varchar(500) NULL COMMENT '상품이미지1',
	GOODS_IMG_PATH2 varchar(500) NULL COMMENT '상품이미지2',
	GOODS_IMG_PATH3 varchar(500) NULL COMMENT '상품이미지3',
	GOODS_IMG_PATH4 varchar(500) NULL COMMENT '상품이미지4',
	GOODS_IMG_PATH5 varchar(500) NULL COMMENT '상품이미지5',
	GOODS_SAME_WORD varchar(500) NULL COMMENT '동의어',
	GOODS_DESC TEXT NULL COMMENT '상품설명',
	VENDOR_STOCK_CNT decimal(15,2) NULL COMMENT '공급사재고수량_최근',
	INSERT_USER_ID VARCHAR(10) NULL COMMENT '등록자ID',
	INSERT_DT DATETIME NULL COMMENT '등록일시',
	UPDATE_USER_ID VARCHAR(10) NULL COMMENT '수정자ID',
	UPDATE_DT DATETIME NULL COMMENT '수정일시',
	ORDER_CNT INT NULL COMMENT '주문횟수',
	USE_ST VARCHAR(1) DEFAULT '1' NULL COMMENT '사용상태',
	DIST_RATE INT NULL COMMENT '물량배분율',
	VENDOR_DISP_NO INT DEFAULT 0 NOT NULL COMMENT '상품우선순위_진열순위',
	SELL_PRICE DECIMAL(15,2) NULL COMMENT '판매가_옵션기본',
	OPT_SELL_ADD_PRICE DECIMAL(15,2) NULL COMMENT '판매가_추가금액',
	BUY_PRICE DECIMAL(15,2) NULL COMMENT '매입가_옵션기본',
	OPT_BUY_ADD_PRICE DECIMAL(15,2) NULL COMMENT '매입가_추가금액',
	BUY_RATE DECIMAL(8, 2) NULL COMMENT '기준매익율',
	VENDOR_STOCK_YN CHAR(1) DEFAULT 'N' NULL COMMENT '공급사재고관리_YN',
	VENDOR_STOCK_SAVE_QUAN INT NULL COMMENT '공급사안전재고수',
	VENDOR_STOCK_SAVE_AUTO CHAR(1) DEFAULT '1' NULL COMMENT '공급사안전재고자동',
	VENDOR_STOCK_SORT INT DEFAULT 0 NULL COMMENT '공급사재고소팅',
	LOGI_ORDER_UNIT VARCHAR(10) NULL COMMENT '주문단위_물류',
	CHG_REASON VARCHAR(500) NULL COMMENT '변경사유',
	ATTACH_SEQ1 VARCHAR(50) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 VARCHAR(50) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 VARCHAR(50) NULL COMMENT '첨부파일3',
	B2C_DISP_YN VARCHAR(1) DEFAULT 'N' NULL COMMENT 'B2C 진열여부_Default:N',
	PRIMARY KEY (GOODS_HIST_ID)
)
COMMENT='상품공급사이력';

CREATE TABLE GDS_GOODS_VENDOR_STOCK_HIST (
	STOCK_CHG_HIST_ID bigint NOT NULL COMMENT '재고변경이력ID',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '공급사ID',
	VENDOR_ID varchar(10) NULL COMMENT '상품코드',
	CHG_REASON varchar(500) NULL COMMENT '변경사유',
	STOCK_TRANS_QUAN int NULL COMMENT '재고증감',
	INSERT_DT datetime NULL COMMENT '등록일',
	INSERT_USER_ID varchar(20) NULL COMMENT '등록자',
	ORDE_IDEN_NO varchar(13) NULL COMMENT '주문번호',
	STOCK_QUAN int NULL COMMENT '남은재고수',
	PRIMARY KEY (STOCK_CHG_HIST_ID)
)
COMMENT='재고변경이력';



