CREATE TABLE PUR_ORD_MAST (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_NM varchar(500) NULL COMMENT '주문명',
	ORDE_TP varchar(10) DEFAULT '10' NOT NULL COMMENT '주문유형',
	GROUP_ID varchar(10) NOT NULL COMMENT '그룹ID',
	CLIENT_ID varchar(10) NOT NULL COMMENT '법인ID',
	BRANCH_ID varchar(10) NOT NULL COMMENT '사업장ID',
	IS_PREPAY varchar(1) DEFAULT 0 NOT NULL COMMENT '선입금여부',
	AREA_TP_CD varchar(10) NULL COMMENT '권역 (DELI_AREA_CODE)',
	ORDE_USER_ID varchar(10) NOT NULL COMMENT '주문자ID',
	ORDE_DT DATETIME NOT NULL COMMENT '주문일시',
	ORDE_TEL_NO varchar(150) NULL COMMENT '주문자전화번호',
	DELI_ADRES varchar(500) NULL COMMENT '배송지주소',
	DELI_USER_NM varchar(50) NULL COMMENT '인수자',
	DELI_USER_TEL_NO varchar(150) NULL COMMENT '인수자전화번호',
	MNG_USER_NM varchar(20) NULL COMMENT '관리자명',
	MNG_USER_TEL_NO varchar(150) NULL COMMENT '관리자연락처',
	ORDE_REQ_NOTE varchar(500) NULL COMMENT '주문요청사항',
	ATTACH_SEQ1 varchar(10) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 varchar(10) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 varchar(10) NULL COMMENT '첨부파일3',
	INSERT_USER_ID varchar(10) NOT NULL COMMENT '등록자ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	LOAN_YN varchar(1) DEFAULT 'N' NOT NULL COMMENT '여신제한YN',
	ORDE_REASON VARCHAR(500) NULL COMMENT '주문사유',
	B2C_YN varchar(1) DEFAULT 'N' NOT NULL COMMENT 'B2C_주문YN',
	PRIMARY KEY (ORDE_IDEN_NO)
)
COMMENT = '주문마스터';

CREATE TABLE PUR_ORD_DETAIL (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NOT NULL COMMENT '주문차수',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	ORDE_ST varchar(10) NULL COMMENT '주문상태 (ORDERSTATUSFLAGCD)',
	DIST_FL varchar(10) not null default '0' COMMENT '물량배분여부',
	ORDE_QUAN decimal(7,0) NULL COMMENT '주문수량',
	PURC_QUAN decimal(7,0) NULL COMMENT '발주수량',
	SELL_PRICE decimal(15,2) NULL COMMENT '판매단가',
	BUY_PRICE decimal(15,2) NULL COMMENT '매입단가',
	TAX_CD varchar(10) NOT null default '10' COMMENT '과세구분 (VTAXTYPECODE)',
	STND_DELI_DAY decimal(2,0) NULL COMMENT '표준납기일자',
	DELI_REQ_DT datetime NULL COMMENT '납품요청일시',
	APP_USER_ID varchar(10) NULL COMMENT '감독자ID',
	APP_DT datetime NULL COMMENT '승인반려일시',
	GOODS_NM varchar(200) NULL COMMENT '상품명',
	GOODS_SPEC varchar(300) NULL COMMENT '상품규격',
	REPRE_GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '옵션대표코드',
	COMMON_OPT varchar(100) DEFAULT ' ' NOT NULL COMMENT '공통옵션',
	LOGI_GOODS_YN VARchar(1) DEFAULT 'N' NULL COMMENT '물류상품여부',
	GOODS_TP_CD varchar(10) not NULL default '10' COMMENT '상품구분 (ORDERGOODSTYPE)',
	ORDE_NM varchar(500) NULL COMMENT '주문명',
	DELI_ADRES varchar(500) NULL COMMENT '배송지주소',
	GOODS_REQ_NOTE varchar(500) NULL COMMENT '상품별 요청사항',
	LOGI_VENDOR_ID varchar(10) NULL COMMENT '물류공급사ID',
	DELI_USER_NM varchar(50) NULL COMMENT '인수자명',
	DELI_USER_TEL_NO varchar(150) NULL COMMENT '인수자전화번호',
	B2C_CANCEL_QUAN int NULL COMMENT '팬타온 취소수량',
	PRIMARY KEY (ORDE_IDEN_NO, ORDE_SEQU_NO)
)
COMMENT = '주문상품';

CREATE TABLE PUR_ORD_SEND (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NOT NULL COMMENT '주문차수',
	PURC_IDEN_NO varchar(2) NOT NULL COMMENT '발주차수',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	SELL_PRICE decimal(15,2) NULL COMMENT '판매단가',
	BUY_PRICE decimal(15,2) NULL COMMENT '매입단가',
	PURC_ST_CD varchar(10) NULL COMMENT '발주상태 (ORDERSTATUSFLAGCD)',
	PURC_QUAN decimal(7,0) NULL COMMENT '발주수량',
	SHIP_QUAN decimal(7,0) NULL COMMENT '출하수량',
	PURC_USER_ID varchar(10) NULL COMMENT '발주의뢰자ID',
	PURC_DT datetime NULL COMMENT '발주의뢰일시',
	PURC_RECE_USER_ID varchar(10) NULL COMMENT '발주접수자ID',
	PURC_RECE_DT datetime NULL COMMENT '발주접수일시',
	SHIP_PLAN_DT datetime NULL COMMENT '납품예정일시',
	LOGI_GOODS_YN VARchar(1) DEFAULT 'N' not NULL COMMENT '물류상품여부',
	NO_BILL_YN VARchar(1) not null default 'N' COMMENT '미수금여부',
	PRIMARY KEY (ORDE_IDEN_NO, ORDE_SEQU_NO, PURC_IDEN_NO)
)
COMMENT = '주문발주';

CREATE TABLE PUR_ORD_SEND_HIST (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NOT NULL COMMENT '주문차수',
	PURC_IDEN_NO varchar(2) NOT NULL COMMENT '발주차수',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	SELL_PRICE decimal(15,2) NULL COMMENT '판매단가',
	BUY_PRICE decimal(15,2) NULL COMMENT '매입단가',
	PURC_ST_CD varchar(10) NULL COMMENT '발주상태 (ORDERSTATUSFLAGCD)',
	PURC_QUAN decimal(7,0) NULL COMMENT '발주수량',
	SHIP_QUAN decimal(7,0) NULL COMMENT '출하수량',
	PURC_USER_ID varchar(10) NULL COMMENT '발주의뢰자ID',
	PURC_DT datetime NULL COMMENT '발주의뢰일시',
	PURC_RECE_USER_ID varchar(10) NULL COMMENT '발주접수자ID',
	PURC_RECE_DT datetime NULL COMMENT '발주접수일시',
	SHIP_PLAN_DT datetime NULL COMMENT '납품예정일시',
	LOGI_GOODS_YN VARchar(1) NULL COMMENT '물류상품여부',
	NO_BILL_YN VARchar(1) NULL COMMENT '미수금여부',
	HIST_INSERT_USER_ID VARCHAR(10) null COMMENT '등록자ID',
	HIST_INSERT_DT DATETIME null COMMENT '등록일시'
)    
COMMENT = '주문발주이력';                   

CREATE TABLE PUR_ORD_SEND_CANCEL (
	CANCEL_ID int NOT NULL COMMENT '취소요청번호',
	ORDE_IDEN_NO varchar(13) NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NULL COMMENT '주문차수',
	PURC_IDEN_NO varchar(2) NULL COMMENT '발주차수',
	CANCEL_ST varchar(20) not null default '0' COMMENT '요청상태',
	REQ_REASON varchar(500) NULL COMMENT '요청사유',
	REJ_REASON varchar(500) NULL COMMENT '거부사유',
	REQ_DT datetime NULL COMMENT '요청일자',
	REQ_USER_ID varchar(10) NULL COMMENT '요청자',
	APP_DT datetime NULL COMMENT '처리일시',
	APP_USER_ID varchar(10) NULL COMMENT '처리자',
	PRIMARY KEY (CANCEL_ID)
)
COMMENT = '발주취소요청';

CREATE TABLE PUR_ORD_SHIP (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NOT NULL COMMENT '주문차수',
	PURC_IDEN_NO varchar(2) NOT NULL COMMENT '발주차수',
	SHIP_IDEN_NO varchar(2) NOT NULL COMMENT '출하차수',
	SHIP_QUAN  decimal(7,0) NULL COMMENT '출하수량',
	RECE_QUAN decimal(7,0) NULL COMMENT '실인수수량',
	SHIP_ST_CD varchar(10) NULL COMMENT '출하상태 (ORDERSTATUSFLAGCD)',
	DELI_COMP_CD varchar(50) NULL COMMENT '배송회사코드 (DELIVERYTYPE)',
	INVOICE_NO varchar(200) NULL COMMENT '송장번호',
	SHIP_USER_ID varchar(10) NULL COMMENT '출하자ID',
	SHIP_DT datetime NULL COMMENT '출하일시',
	RECE_USER_ID varchar(10) NULL COMMENT '인수자ID',
	RECE_DT datetime NULL COMMENT '인수일시',
	IS_DELI_DONE char(1) not null default '0' COMMENT '베송완료여부',
	RECEIPT_NO varchar(30) NULL COMMENT '인수증출력번호',
	RETU_IDEN_NO int NULL COMMENT '반품번호',
	SHIP_ATTACH_SEQ varchar(10) NULL COMMENT '출하성적서업로드파일',
	INVOICE_INSERT_DT datetime NULL COMMENT '송장등록일시',
	INVOICE_INSERT_USER_ID varchar(10) NULL COMMENT '송장등록자ID',
	SHIP_NOTE TEXT NULL COMMENT '출하코맨트',
	LOGI_GOODS_YN VARchar(1) DEFAULT 'N' NOT NULL COMMENT '물류상품여부',
	PRIMARY KEY (ORDE_IDEN_NO, ORDE_SEQU_NO, PURC_IDEN_NO, SHIP_IDEN_NO)
)
COMMENT = '주문출고';

CREATE TABLE PUR_ORD_RECEIVE (
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NOT NULL COMMENT '주문차수',
	PURC_IDEN_NO varchar(2) NOT NULL COMMENT '발주차수',
	SHIP_IDEN_NO varchar(2) NOT NULL COMMENT '출하차수',
	RECE_IDEN_NO varchar(2) NOT NULL COMMENT '인수차수',
	ORDE_TP_CD varchar(10) not null default '10' COMMENT '주문유형 (ORDERTYPECODE)',
	GROUP_ID varchar(10) NULL COMMENT '그룹ID',
	CLIENT_ID varchar(10) NULL COMMENT '법인ID',
	BRANCH_ID varchar(10) NULL COMMENT '사업장ID',
	ORDE_DT datetime NULL COMMENT '주문일시',
	SHIP_DT datetime NULL COMMENT '출하일시',
	RECE_DT datetime NULL COMMENT '인수일시',
	AREA_TP_CD varchar(10) NULL COMMENT '권역 (DELI_AREA_CODE)',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	ORDE_NM varchar(500) NULL COMMENT '주문명',
	TAX_CD varchar(10) NOT null default '10' COMMENT '과세구분 (VTAXTYPECODE)',
	RECE_QUAN decimal(7,0) NULL COMMENT '인수수량',
	SELL_PRICE decimal(15,2) NULL COMMENT '매출단가',
	SELL_AMT decimal(15,2) NULL COMMENT '매출금액',
	BUY_PRICE decimal(15,2) NULL COMMENT '매입단가',
	BUY_AMT decimal(15,2) NULL COMMENT '매입금액',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	GOODS_NM varchar(200) NULL COMMENT '상품명',
	ORDE_USER_ID varchar(10) NULL COMMENT '주문자',
	RECE_USER_ID varchar(10) NULL COMMENT '인수처리자ID',
	SELL_SEQU_NO varchar(10) not null default '0' COMMENT '매출ID',
	BUY_SEQU_NO varchar(10) not null default '0' COMMENT '매입ID',
	GOODS_SPEC varchar(300) NULL COMMENT '상품규격',
	ADD_REPRE_SEQU_NO varchar(3) NULL COMMENT '추가상품 대표 주문차수',
	REPRE_GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '옵션대표코드',
	LOGI_GOODS_YN VARchar(1) not null DEFAULT 'N' COMMENT '물류상품여부',
	PRIMARY KEY (ORDE_IDEN_NO, ORDE_SEQU_NO, PURC_IDEN_NO, SHIP_IDEN_NO, RECE_IDEN_NO)
)
COMMENT = '주문인수';

CREATE TABLE PUR_ORD_RETURN (
	RETU_IDEN_NO int NOT NULL COMMENT '반품번호',
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NOT NULL COMMENT '주문차수',
	SHIP_IDEN_NO varchar(2) NOT NULL COMMENT '출하차수',
	RECE_IDEN_NO varchar(2) NOT NULL COMMENT '인수차수',
	PURC_IDEN_NO varchar(2) NOT NULL COMMENT '발주차수',
	RETU_ST_CD varchar(10) NOT null default '0' COMMENT '처리상태 (RETURNSTATUSFLAG)',
	RETU_QUAN decimal(7,0) NULL COMMENT '교환반품수량',
	REQ_USER_ID varchar(10) NULL COMMENT '요청자ID',
	REQ_DT datetime NULL COMMENT '요청일시',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	REQ_REASON TEXT NULL COMMENT '요청사유',
	APP_REASON TEXT NULL COMMENT '처리사유',
	APP_USER_ID varchar(10) NULL COMMENT '처리자ID',
	APP_DT datetime NULL COMMENT '처리일시',
	PRIMARY KEY (RETU_IDEN_NO)
)
COMMENT = '주문교환반품';

CREATE TABLE PUR_ORD_HIST (
	ORDE_HIST_NO varchar(10) NOT NULL COMMENT '주문히스토리SEQ',
	ORDE_IDEN_NO varchar(13) NOT NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NOT NULL COMMENT '주문차수',
	PURC_IDEN_NO varchar(2) NULL COMMENT '발주차수',
	SHIP_IDEN_NO varchar(2) NULL COMMENT '출하차수',
	RECE_IDEN_NO varchar(2) NULL COMMENT '인수차수',
	CHG_TEXT varchar(500) NULL COMMENT '변경내용',
	CHG_REASON varchar(1000) NULL COMMENT '변경사유',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	INSERT_DT datetime NULL COMMENT '등록일시',
	INSERT_BORG_ID varchar(10) null COMMENT '등록자 조직ID',
	PRIMARY KEY (ORDE_HIST_NO)
)                 
COMMENT = '주문상품이력';

CREATE TABLE PUR_CART (
	CART_ID int NOT NULL COMMENT '장바구니 ID',
	CART_NM varchar(100) default '기본' NOT NULL COMMENT '장바구니명',
	BRANCH_ID varchar(10) NOT NULL COMMENT '사업장ID',
	USER_ID varchar(10) NOT NULL COMMENT '사용자ID',
	DEFAULT_YN char(1) default 'Y' NOT NULL COMMENT '기본_YN',
	COMP_ID int NULL COMMENT '공사ID',
	ORDE_REQ_NOTE varchar(500) NULL COMMENT '주문요청사항',
	ORDE_REASON varchar(500) NULL COMMENT '주문사유',
	DELI_ADRES_ID varchar(10) NULL COMMENT '배송지ID',
	DELI_USER_NM varchar(50) NULL COMMENT '인수자명',
	DELI_USER_TEL_NO varchar(150) NULL COMMENT '인수자연락처',
	ATTACH_SEQ1 varchar(10) NULL COMMENT '첨부파일1',
	ATTACH_SEQ2 varchar(10) NULL COMMENT '첨부파일2',
	ATTACH_SEQ3 varchar(10) NULL COMMENT '첨부파일3',
	PRIMARY KEY (CART_ID)
)
COMMENT = '장바구니';

CREATE TABLE PUR_CART_GOODS (
	CART_ID int NOT NULL COMMENT '장바구니 ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	REPRE_GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '옵션대표상품코드',
	COMMON_OPT varchar(100) DEFAULT '' NOT NULL COMMENT '공통옵션',
	ORDE_QUAN decimal(7,0) NOT NULL COMMENT '주문수량',
	INSERT_DT datetime NOT NULL COMMENT '등록일시',
	PRIMARY KEY (CART_ID, GOOD_IDEN_NO, VENDOR_ID, COMMON_OPT)
)
COMMENT = '장바구니 품목';

CREATE TABLE PUR_CART_COMP (
	COMP_ID int NOT NULL COMMENT '공사ID',
	BRANCH_ID varchar(10) NULL COMMENT '사업장ID',
	USER_ID varchar(10) NULL COMMENT '사용자ID',
	ORDE_NM varchar(500) NULL COMMENT '주문명',
	COMP_YM varchar(6) NULL COMMENT '사업년월',
	COMP_SI varchar(20) NULL COMMENT '공사시도',
	COMP_GU varchar(20) NULL COMMENT '공사시군구',
	PRIMARY KEY (COMP_ID)
)
COMMENT = '공사정보';

CREATE TABLE PUR_USER_GOODS (
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	BRANCH_ID varchar(10) NOT NULL COMMENT '사업장ID',
	USER_ID varchar(10) NOT NULL COMMENT '사용자ID',
	VENDOR_ID varchar(20) DEFAULT 0 NOT NULL COMMENT '공급사ID',
	INSERT_DT datetime NULL COMMENT '등록일시',
	PRIMARY KEY (GOOD_IDEN_NO, BRANCH_ID, USER_ID, VENDOR_ID)
)
COMMENT = '관심상품';

CREATE TABLE PUR_DELIVERY_INFO (
	DELI_ADRES_ID varchar(10) NOT NULL COMMENT '배송처ID',
	GROUP_ID varchar(10) NULL COMMENT '그룹ID',
	CLIENT_ID varchar(10) NULL COMMENT '법인ID',
	BRANCH_ID varchar(10) NOT NULL COMMENT '사업장ID',
	DELI_NM varchar(50) NULL COMMENT '배송지명',
	DELI_ADRES varchar(1000) NULL COMMENT '배송지주소',
	DELI_TEL_NO varchar(150) NULL COMMENT '배송지기본연락처',
	IS_DEFAULT varchar(2) NULL COMMENT '기본배송지여부',
	DELI_USER_NM varchar(50) NULL COMMENT '인수자',
	DELI_USER_TEL_NO varchar(150) NULL COMMENT '인수자 전화번호',
	INSERT_DT datetime NULL COMMENT '등록일시',
	INSERT_USER_ID varchar(10) null COMMENT '등록자ID',
	PRIMARY KEY (DELI_ADRES_ID)
)
COMMENT = '조직배송지';

CREATE TABLE PUR_DIRECT_INFO (
	BRANCH_ID varchar(10) NOT NULL COMMENT '사업장ID',
	APP_USER_ID varchar(10) NOT null COMMENT '감독사용자ID',
	USER_ID varchar(10) NOT NULL COMMENT '피감독사용자(주문자)ID',
	INSERT_DT DATETIME null COMMENT '등록일시',
	INSERT_USER_ID VARCHAR(10) null COMMENT '등록자ID',
	PRIMARY KEY (BRANCH_ID, APP_USER_ID, USER_ID)
)                 
COMMENT = '감독정보';
