CREATE TABLE WMS_STOCK (
	BARCODE varchar(40) NOT NULL COMMENT '바코드번호',
	BARCODE_SEQ varchar(2) DEFAULT 1 NOT NULL COMMENT '바코드차수_반품입고또는센터간이동시',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NULL COMMENT '공급사ID',
	BORG_ID varchar(10) NULL COMMENT '센터ID',
	BARCODE_IMG_PATH varchar(400) NULL COMMENT '바코드이미지경로',
	SUPPLY_QUAN int NULL COMMENT '공급사배송수_발주수',
	SUPPLY_REAL_QUAN int NULL COMMENT '공급사실배송수_입고접수수',
	STOCK_CHECK_QUAN int NULL COMMENT '품질검사대기수',
	ENTERING_QUAN int NULL COMMENT '입고대기수',
	GOOD_QUAN int NULL COMMENT '양품수',
	BAD_QUAN int NULL COMMENT '불량수',
	SHIPPING_QUAN int NULL COMMENT '출고대기수',
	SHIPPED_QUAN int NULL COMMENT '반품입고대기수',
	RETURN_ENTERING_QUAN int NULL COMMENT '출고된수량',
	ENTER_ST int NULL COMMENT '재고입고상태',
	SUPPLY_USER_ID varchar(10) NULL COMMENT '공급사출고자ID',
	SUPPLY_DT datetime NULL COMMENT '공급사출고일시',
	ENTER_USER_ID varchar(10) NULL COMMENT '창고입고자ID',
	ENTER_DT datetime NULL COMMENT '창고입고일시',
	STOCK_ORDE_IDEN_NO varchar(13) NULL COMMENT '입고주문번호',
	STOCK_ORDE_SEQU_NO varchar(3) NULL COMMENT '입고주문차수',
	STOCK_PURC_IDEN_NO varchar(2) NULL COMMENT '입고발주차수',
	RETU_IDEN_NO int NULL COMMENT '반품번호',
	MOVE_REQ_ID int NULL COMMENT '센터간이동번호',
	ENTER_TYPE_CD varchar(1) NOT NULL DEFAULT '0' COMMENT '입고유형 (ENTER_TYPE)',
	RETU_MAPPING_YN varchar(1) NOT NULL DEFAULT 'N' COMMENT '반품매핑대상_Y',
	BUY_PRICE decimal(15,2) NULL COMMENT '매입단가',
	PRIMARY KEY (BARCODE, BARCODE_SEQ)
)
COMMENT = '물류재고정보';

CREATE TABLE WMS_STOCK_HIST (
	BARCODE varchar(40) not NULL COMMENT '바코드번호',
	BARCODE_SEQ varchar(2) DEFAULT 1 NOT NULL COMMENT '바코드차수_반품입고또는센터간이동시',
	PROCESS_CONTENTS varchar(1000) NULL COMMENT '처리사유',
	PROCESS_TYPE_CD varchar(10) NULL COMMENT '처리유형 (STOCK_HIST_TYPE)',
	PROCESS_QUAN int NULL COMMENT '처리수',
	STOCK_CHECK_QUAN int NULL COMMENT '품질검사대기수',
	ENTERING_QUAN int NULL COMMENT '입고대기수',
	GOOD_QUAN int NULL COMMENT '양품수',
	BAD_QUAN int NULL COMMENT '불량수',
	SHIPPING_QUAN int NULL COMMENT '출고대기수',
	SHIPPED_QUAN int NULL COMMENT '출고된수량',
	RETURN_ENTERING_QUAN int NULL COMMENT '반품입고대기수',
	INSERT_USER_ID varchar(10) NULL COMMENT '등록자ID',
	INSERT_DT datetime nulL COMMENT '등록일시'
)
COMMENT = '물류상품 재고 이력';


CREATE TABLE WMS_SHIP_MAST (
	SHIP_NO varchar(20) NOT NULL COMMENT '출고번호',
	BOX_TYPE_CD varchar(20) NULL COMMENT '박스유형 (LOGI_BOX)',
	INSERT_USER_ID varchar(10) NULL COMMENT '생성자ID',
	INSERT_DT datetime NULL COMMENT '생성일시',
	PRIMARY KEY (SHIP_NO)
)
COMMENT = '출고마스터';


CREATE TABLE WMS_SHIP_MOVE_REQ (
	MOVE_REQ_ID int NOT NULL COMMENT '센터간이동번호',
	SHIP_BORG_ID varchar(10) NULL COMMENT '출고센터ID',
	SHIP_USER_ID varchar(10) NULL COMMENT '출고요청자ID',
	SHIP_QUAN int NULL COMMENT '출고요청수량',
	ENTER_BORG_ID varchar(10) NULL COMMENT '입고센터ID',
	SHIP_REQ_DT datetime NULL COMMENT '출고요청일시',
	SHIP_PLAN_DT datetime NULL COMMENT '출고예정일',
	SHIP_REQ_ST varchar(1) not NULL DEFAULT '0' COMMENT '출고요청상태',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	PRIMARY KEY (MOVE_REQ_ID)
)
COMMENT = '센터간이동요청';

CREATE TABLE WMS_SHIP_PACKING (
	SHIP_NO varchar(20) NOT NULL COMMENT '출고번호',
	SHIPPING_ID int NOT NULL COMMENT '출고상세번호',
	PACKING_QUAN int NULL COMMENT '패킹수량',
	PRIMARY KEY (SHIP_NO, SHIPPING_ID)
)
COMMENT = '출고패킹';

CREATE TABLE WMS_SHIPPING (
	SHIPPING_ID int NOT NULL COMMENT '출고상세번호',
	ORDE_IDEN_NO varchar(13) NULL COMMENT '주문번호',
	ORDE_SEQU_NO varchar(3) NULL COMMENT '주문차수',
	PURC_IDEN_NO varchar(2) NULL COMMENT '발주차수',
	BARCODE varchar(40) NOT NULL COMMENT '바코드번호',
	BARCODE_SEQ varchar(2) DEFAULT 1 NOT NULL COMMENT '바코드차수_반품입고또는센터간이동시',
	SHIPPING_QUAN int NULL COMMENT '출고수량',
	SHIPPING_ST VARchar(1) not NULL DEFAULT 1 COMMENT '물류출고상태',
	MOVE_REQ_ID int NULL COMMENT '센터간이동번호',
	SHIP_NO varchar(20) NULL COMMENT '출고번호',
	SHIP_TP varchar(1) not NULL DEFAULT '0' COMMENT '출고유형',
	SERIAL_NO varchar(500) NULL COMMENT '제조번호',
	PRIMARY KEY (SHIPPING_ID)
)
COMMENT = '출고상세';

CREATE TABLE WMS_EXAM_RETURN (
	EXAM_ID int NOT NULL COMMENT '검사번호',
	BARCODE varchar(40) NOT NULL COMMENT '바코드번호',
	BARCODE_SEQ varchar(2) DEFAULT 1 NOT NULL COMMENT '바코드차수_반품입고또는센터간이동시',
	EXAM_TP VARchar(1) not NULL DEFAULT 1 COMMENT '검사유형',
	EXAM_QUAN int NULL COMMENT '검사수',
	GOOD_QUAN int NULL COMMENT '양품수',
	BAD_QUAN int NULL COMMENT '불량수',
	TEST_QUAN int NULL COMMENT '테스트수량',
	ATTACH_SEQ int NULL COMMENT '첨부파일SEQ',
	EXAM_ITEM varchar(500) NULL COMMENT '검사항목',
	EXAM_CONTENTS varchar(2000) NULL COMMENT '검사내용',
	EXAM_YN VARchar(1) not NULL DEFAULT 'N' COMMENT '검사여부_YN',
	EXAM_USER_ID varchar(10) NULL COMMENT '검사자ID',
	EXAM_DT datetime NULL COMMENT '검사일시',
	INSERT_USER_ID varchar(10) NULL COMMENT '생성자ID',
	INSERT_DT datetime NULL COMMENT '생성일시',
	REMOVE_TARGET_YN VARchar(1) not NULL DEFAULT 'N' COMMENT '반환대상_YN',
	REQ_ID int NULL COMMENT '반환요청번호',
	REMOVE_ST VARchar(1) NULL COMMENT '반환상태',
	REMOVE_COMP_USER_ID varchar(10) NULL COMMENT '반환완료자ID',
	REMOVE_COMP_DT datetime NULL COMMENT '반환완료일시',
	`ANALYZE` varchar(2000) NULL COMMENT '원인분석',
	IMPROVE varchar(2000) NULL COMMENT '개선대책',
	ATTACH_SEQ1 int NULL COMMENT '분석첨부파일1',
	ATTACH_SEQ2 int NULL COMMENT '분석첨부파일2',
	PRIMARY KEY (EXAM_ID, BARCODE, BARCODE_SEQ)
)
COMMENT = '품질검사 반환 정보';

CREATE TABLE WMS_GOODS_RETURN (
	REQ_ID int NOT NULL COMMENT '반환요청번호',
	BARCODE varchar(40) NOT NULL COMMENT '바코드번호',
	BARCODE_SEQ varchar(2) DEFAULT 1 NOT NULL COMMENT '바코드차수_반품입고또는센터간이동시',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	RETURN_QUAN int NOT NULL COMMENT '반환개수',
	RETURN_ST VARchar(1) NOT NULL DEFAULT '0' COMMENT '반환상태',
	REQ_USER_ID varchar(10) NULL COMMENT '반환신청자ID',
	REQ_DT datetime NULL COMMENT '반환신청일시',
	COMP_USER_ID varchar(10) NULL COMMENT '반환완료일시',
	COMP_DT datetime NULL COMMENT '반환완료자ID',
	APP_USER_ID varchar(10) NULL COMMENT '승인자ID',
	APP_DT datetime NULL COMMENT '승인일시',
	RETU_SCHE_DT datetime NULL COMMENT '반환예정일',
	PRIMARY KEY (REQ_ID, BARCODE, BARCODE_SEQ)
)
COMMENT = '양품 물류 반환';

CREATE TABLE WMS_RETURN_REQ (
	REQ_ID int NOT NULL COMMENT '반환요청번호',
	REQ_USER_ID varchar(10) NULL COMMENT '반환요청자ID',
	REQ_DT datetime NULL COMMENT '반환요청일시',
	APP_USER_ID varchar(10) NULL COMMENT '승인자ID',
	APP_DT datetime NULL COMMENT '승인일시',
	RETU_SCHE_DT datetime NULL COMMENT '반환예정일',
	PRIMARY KEY (REQ_ID)
)
COMMENT = '물류 반환 요청';

CREATE TABLE WMS_SAFE_STOCK (
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	BORG_ID varchar(10) NOT NULL COMMENT '센터ID',
	SAFE_STOCK_QUAN int NULL COMMENT '적정재고수',
	STOCK_PROPER_FLAG varchar(1) not NULL DEFAULT '5' COMMENT '적정재고산출',
	STOCK_PROPER_RATE int NULL COMMENT '적정재고산출추가비율',
	STOCK_OVER_RATE int NULL COMMENT '적정재고메시지과부족율',
	IS_STOCK_OVER_MSG varchar(1) DEFAULT 0 not NULL COMMENT '적정재고 메세지 여부',
	PRIMARY KEY (GOOD_IDEN_NO, BORG_ID)
)
COMMENT = '물류 적정 재고';

CREATE TABLE WMS_REAL_SEARCH (
	INVENTORY_ID int NOT NULL COMMENT '재고조사ID',
	BORG_ID varchar(10) NOT NULL COMMENT '조직ID',
	BARCODE varchar(40) NULL COMMENT '바코드번호',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	VENDOR_ID varchar(10) NOT NULL COMMENT '공급사ID',
	STOCK_CHECK_QUAN int DEFAULT 0 NULL COMMENT '검사대기실사수',
	STOCK_CHECK_SYS_QUAN int DEFAULT 0 NULL COMMENT '검사대기SYS수',
	ENTERING_QUAN int DEFAULT 0 NULL COMMENT '입고대기실사수',
	ENTERING_SYS_QUAN int DEFAULT 0 NULL COMMENT '입고대기SYS수',
	GOOD_QUAN int DEFAULT 0 NULL COMMENT '양품실사수',
	GOOD_SYS_QUAN int DEFAULT 0 NULL COMMENT '양품SYS수',
	SHIPPING_QUAN int DEFAULT 0 NULL COMMENT '주문출고대기실사수',
	SHIPPING_SYS_QUAN int DEFAULT 0 NULL COMMENT '주문출고대기SYS수',
	BAD_QUAN int DEFAULT 0 NULL COMMENT '불량실사수',
	BAD_SYS_QUAN int DEFAULT 0 nulL COMMENT '불량SYS수'
)
COMMENT = '물류재고 실사';

CREATE TABLE WMS_STOCK_CHG_REQ (
	REQ_ID int NOT NULL COMMENT '재고조정요청ID',
	BORG_ID varchar(10) NOT NULL COMMENT '센터ID',
	GOOD_IDEN_NO VARCHAR(20) NOT NULL COMMENT '상품코드',
	BARCODE varchar(40) NOT NULL COMMENT '바코드',
	CHG_FLAG varchar(1) not NULL COMMENT '증/차감_증가:1_차감:0',
	TRANS_CNT int NULL COMMENT '처리수',
	REQ_COMMENT varchar(2000) NULL COMMENT '요청사유',
	REQ_ST varchar(1) not NULL DEFAULT '0' COMMENT '상태',
	REQ_DT datetime NULL COMMENT '요청일시',
	REQ_USER_ID varchar(10) NULL COMMENT '요청자ID',
	APP_DT datetime NULL COMMENT '승인/반려일시',
	APP_USER_ID varchar(10) NULL COMMENT '승인/반려자ID',
	ADD_BARCODE varchar(40) NULL COMMENT '증가바코드',
	PRIMARY KEY (REQ_ID)
)
COMMENT = '물류재고 조정 요청';

CREATE TABLE WMS_INVENTORY (
	INVENTORY_ID int NOT NULL COMMENT '재고조사ID',
	BORG_ID varchar(10) NULL COMMENT '센터ID',
	INVENTORY_ST VARchar(1) NOT NULL DEFAULT '0' COMMENT '조사상태',
	CONTENTS varchar(1000) NULL COMMENT '조사내용',
	INSERT_USER_ID varchar(10) NULL COMMENT '생성자ID',
	INSERT_DT datetime NULL COMMENT '생성일시',
	UPDATE_USER_ID varchar(10) NULL COMMENT '수정자ID',
	UPDATE_DT datetime NULL COMMENT '수정일시',
	APPROVE_ID varchar(10) NULL COMMENT '승인자ID',
	APPROVE_DT datetime NULL COMMENT '승인일시',
	INSERT_BORG_ID varchar(10) NULL COMMENT '생성자조직ID',
	REVIEW_USER_ID varchar(10) NULL COMMENT '검토자ID',
	REVIEW_DT datetime NULL COMMENT '검토일시',
	COMPLETE_USER_ID varchar(10) NULL COMMENT '완료자ID',
	COMPLETE_DT datetime NULL COMMENT '완료일',
	PRIMARY KEY (INVENTORY_ID)
)
COMMENT = '물류재고 조사';

CREATE TABLE WMS_LOCATION (
	LOC_ID varchar(10) NOT NULL COMMENT '로케이션 ID',
	LOC_CD varchar(10) NOT NULL COMMENT '로케이션CD',
	BORG_ID varchar(10) NOT NULL COMMENT '센터ID',
	PAR_LOC_ID varchar(10) NOT NULL DEFAULT '0' COMMENT '부모ID',
	LEVEL int DEFAULT 1 not NULL COMMENT '레벨',
	LOC_DESC varchar(2000) NULL COMMENT '로케이션 설명',
	DISP_NO int DEFAULT 1 not NULL COMMENT '순서',
	IS_USE VARchar(1) DEFAULT '1' NOT NULL COMMENT '사용여부',
	INSERT_USER_ID varchar(10) NOT NULL COMMENT '등록자 ID',
	INSERT_DT datetime NOT NULL COMMENT '등록일',
	UPDATE_USER_ID varchar(10) NULL COMMENT '수정자 ID',
	UPDATE_DT datetime NULL COMMENT '수정일',
	PRIMARY KEY (LOC_ID)
)
COMMENT = '로케이션';


CREATE TABLE WMS_LOCATION_STOCK (
	LOC_ID varchar(10) NULL COMMENT '로케이션 ID',
	BARCODE varchar(40) not NULL COMMENT '바코드번호',
	BARCODE_SEQ varchar(2) NULL COMMENT '바코드차수_반품입고또는센터간이동시',
	BORG_ID varchar(10) nulL COMMENT '센터ID'
)
COMMENT = '로케이션 재고';

CREATE TABLE WMS_PAST_STOCK (
	BORG_ID varchar(10) NULL COMMENT '센터ID',
	GOOD_IDEN_NO VARCHAR(20) NULL COMMENT '상품코드',
	SAFE_STOCK_QUAN int NULL COMMENT '적정재고',
	RECEIVE_READY_QUAN int NULL COMMENT '입고접수대기',
	STOCK_CHECK_QUAN int NULL COMMENT '품질검사대기',
	ENTERING_QUAN int NULL COMMENT '입고확정',
	GOOD_QUAN int NULL COMMENT '양품',
	OUT_READY int NULL COMMENT '출고접수대기',
	SHIPPING_QUAN int NULL COMMENT '출고확정대기',
	BAD_QUAN int NULL COMMENT '불량',
	STOCK_PRICE decimal(15,2) NULL COMMENT '재고금액',
	STOCK_DT datetime NULL COMMENT '재고기준일자',
	BARCODE varchar(40) not NULL COMMENT '바코드',
	ENTER_DT datetime nulL COMMENT '창고입고일자'
)
COMMENT = '물류재고 과거 재고 이력';

