SELECT	A.BI_NO 
,		A.BI_NAME 
,		A.BI_MODE 
,		A.INS_MODE 
,		A.BID_JOIN_SPEC 
,		A.SPECIAL_COND 
,		A.SUPPLY_COND 
,		A.SPOT_DATE 
,		A.SPOT_AREA 
,		A.SUCC_DECI_METH 
,		A.BID_OPEN_DATE 
,		A.AMT_BASIS 
,		A.BD_AMT 
,		A.SUCC_AMT 
,		A.EST_START_DATE 
,		A.EST_CLOSE_DATE 
,		A.EST_OPENER 
,		A.EST_OPEN_DATE 
,		A.OPEN_ATT1 
,		A.OPEN_ATT1_SIGN 
,		A.OPEN_ATT2 
,		A.OPEN_ATT2_SIGN 
,		CASE 	WHEN (A.CREATE_DATE < '2024-01-01' AND A.ING_TAG IN ('A0', 'A1', 'A2', 'A3')) OR A.ING_TAG IS NULL THEN 'A7'
				ELSE A.ING_TAG 
		END AS ING_TAG 
,		A.CREATE_USER 
,		A.CREATE_DATE 
,		A.UPDATE_USER 
,		A.UPDATE_DATE 
,		A.ITEM_CODE 
,		A.GONGO_ID 
,		A.PAY_COND 
,		A.WHY_A3 
,		CASE	WHEN (A.CREATE_DATE < '2024-01-01' AND A.ING_TAG IN ('A0', 'A1', 'A2', 'A3')) OR A.ING_TAG IS NULL THEN 'MIG에 의한 유찰처리(기존상태:'||A.ING_TAG||')' 
				ELSE A.WHY_A7
		END AS WHY_A7
,		A.BI_OPEN 
,		A.INTERRELATED_CUST_CODE 
,		A.REAL_AMT 
,		A.ADD_ACCEPT 
,		A.MAT_DEPT 
,		A.MAT_PROC 
,		A.MAT_CLS 
,		A.MAT_FACTORY 
,		A.MAT_FACTORY_LINE 
,		A.MAT_FACTORY_CNT 
FROM 	T_BI_INFO_MAT A