SELECT 	A.BI_NO 
,		A.CUST_CODE 
,		A.BI_ORDER 
,		A.REBID_ATT 
,		A.ESMT_YN
,		A.ESMT_AMT 
,		A.SUCC_YN 
,		A.FILE_ID 
,		A.SUBMIT_DATE 
,		A.CREATE_USER 
,		A.CREATE_DATE 
,		A.UPDATE_USER 
,		A.UPDATE_DATE 
,		A.ESMT_CURR 
,		TO_CLOB(A.ENC_QUTN) || TO_CLOB(A.ENC_QUTN_SUB) AS ENC_QUTN 
,		A.ENC_ESMT_SPEC 
,		A.USEMAIL_ID 
FROM 	T_BI_INFO_MAT_CUST_TEMP A

