SELECT	(A.ORDE_IDEN_NUMB+'-'+A.ORDE_SEQU_NUMB+'-'+A.PURC_IDEN_NUMB+'-'+A.DELI_IDEN_NUMB+'-'+A.RECE_IDEN_NUMB) AS FULL_ORDE_NUMB	--주문전체번호(주문번호-주문차수-발주차수-출하차수-인수차수), VARCHAR(30)
--,		A.CLIENTID	--주문법인ID, VARCHAR(10)
--,		B.BORGNM AS CLIENTNM	--주문법인명, VARCHAR(100)
--,		A.BRANCHID	--주문사업장ID, VARCHAR(10)
,		C.BORGCD AS BRANCHCD	--주문사업장CD, VARCHAR(10)
,		C.BORGNM AS BRANCHNM	--주문사업장명, VARCHAR(100)
--,		A.ORDE_USER_ID	--주문자ID, VARCHAR(10)
,		E.LOGINID	--로그인ID, VARCHAR(30)
,		E.USERNM	--주문자명, VARCHAR(100)
,		CONVERT(VARCHAR(20), A.ORDE_REGI_DATE, 120) AS ORDE_REGI_DATE	--주문일시, VARCHAR(20)
,		CONVERT(VARCHAR(20), A.RECE_REGI_DATE, 120) AS RECE_REGI_DATE	--인수(입고)일시, VARCHAR(20)
--,		A.VENDORID	--공급사ID, VARCHAR(10)
,		D.BORGCD AS VENDORCD	--공급사CD, VARCHAR(10)
,		D.BORGNM AS VENDORNM	--공급사명, VARCHAR(100)
,		A.CONS_IDEN_NAME	--공사(주문)명, VARCHAR(500)
,		A.SALE_PROD_QUAN	--인수(입고)수량, DECIMAL(7,0)
,		A.SALE_PROD_PRIS	--상품단가, DECIMAL(15,0)
,		A.SALE_PROD_AMOU	--주문금액, DECIMAL(15,0)
,		A.GOOD_IDEN_NUMB	--상품코드, BIGINT
,		A.GOOD_NAME	--상품명, VARCHAR(200)
,		A.GOOD_SPEC	--상품규격, VARCHAR(300)
,		F.ORDER_UNIT	--주문단위, VARCHAR(10)

,		'https://www.okplaza.kr/system/popNoLoginUBForm.sys?fullOrdeNumb='+(A.ORDE_IDEN_NUMB+'-'+A.ORDE_SEQU_NUMB+'-'+A.PURC_IDEN_NUMB+'-'+A.DELI_IDEN_NUMB+'-'+A.RECE_IDEN_NUMB) AS RECE_URL
/*
,		'https://www.okplaza.kr/system/popUBForm.sys?formName=receivePrint&receipt_num=499841&faxnum=051-809-0175&ordeTeleNumb=051-809-0175&tranDataAddr=15361 경기 안산시 단원구 고잔동 540-16 7층 SK브로드밴드&tranTeleNumb=010-8792-0306&clientFaxNumb=051-809-0175'
,		G.RECEIPT_NUM
,		D1.FAXNUM
,		H.ORDE_TELE_NUMB
,		ISNULL(I.TRAN_DATA_ADDR, H.TRAN_DATA_ADDR)	AS TRAN_DATA_ADDR
,		H.TRAN_TELE_NUMB
,		C1.FAXNUM AS CLIENT_FAX_NUM
*/
FROM	MRORDTLIST A WITH(NOLOCK)
LEFT OUTER JOIN SMPBORGS B WITH(NOLOCK)
	ON	B.BORGID = A.CLIENTID
LEFT OUTER JOIN SMPBORGS C WITH(NOLOCK)
	ON	C.BORGID = A.BRANCHID
LEFT OUTER JOIN SMPBRANCHS C1 WITH(NOLOCK)
	ON	C1.BRANCHID = A.BRANCHID
LEFT OUTER JOIN SMPBORGS D WITH(NOLOCK)
	ON	D.BORGID = A.VENDORID
LEFT OUTER JOIN SMPVENDORS D1 WITH(NOLOCK)
	ON	D1.VENDORID = A.VENDORID
LEFT OUTER JOIN SMPUSERS E WITH(NOLOCK)
	ON	E.USERID = A.ORDE_USER_ID
LEFT OUTER JOIN MCGOOD F WITH(NOLOCK)
	ON	F.GOOD_IDEN_NUMB = A.GOOD_IDEN_NUMB
/*
INNER JOIN MRACPT G WITH(NOLOCK)
	ON	G.ORDE_IDEN_NUMB = A.ORDE_IDEN_NUMB
	AND	G.ORDE_SEQU_NUMB = A.ORDE_SEQU_NUMB
	AND	G.PURC_IDEN_NUMB = A.PURC_IDEN_NUMB
	AND	G.DELI_IDEN_NUMB = A.DELI_IDEN_NUMB
INNER JOIN MRORDM H WITH(NOLOCK)
	ON	H.ORDE_IDEN_NUMB = A.ORDE_IDEN_NUMB
INNER JOIN MRORDT I WITH(NOLOCK)
	ON	I.ORDE_IDEN_NUMB = A.ORDE_IDEN_NUMB
	AND	I.ORDE_SEQU_NUMB = A.ORDE_SEQU_NUMB
*/
WHERE	A.CLIENTID = '305786'	--TNS법인
AND		A.ORDE_REGI_DATE > '20200401'
--AND		A.SALE_PROD_QUAN < 0
ORDER BY A.RECE_REGI_DATE DESC