SELECT	A.BORGCD AS BRANCHCD
,		A.BORGNM AS BRANCHNM
FROM	SMPBORGS A WITH(NOLOCK)
WHERE	A.CLIENTID = '305786'
AND		A.ISUSE = '1'
ORDER BY A.BORGCD


SELECT	C.BORGCD AS BRANCHCD
,		C.BORGNM AS BRANCHNM
,		A.LOGINID
,		A.USERNM
FROM	SMPUSERS A WITH(NOLOCK)
INNER JOIN SMPBORGS_USERS B WITH(NOLOCK)
	ON	B.USERID = A.USERID
INNER JOIN SMPBORGS C WITH(NOLOCK)
	ON	C.BORGID = B.BORGID
	AND	C.ISUSE = '1'
WHERE	C.CLIENTID = '305786'
AND		A.ISUSE = '1'
ORDER BY C.BORGCD