/*
SELECT * FROM SMPWORKINFO --53 A¸Á ºÎ´ë¹°ÀÚ

SELECT * fROM SMPBORGS WHERE BORGID = '305786'
SELECT * FROM SMPBORGS WHERE BORGNM LIKE '%TNS%'

--SELECT BORGID FROM SMPBORGS WHERE PARBORGID = '305786' AND ISUSE = '1'
--SELECT * FROM SMPBORGS WHERE PARBORGID = '305786' AND ISUSE = '1'
*/

SELECT	DISTINCT
		CCC.GOOD_IDEN_NUMB
,		CCC.GOOD_NAME
,		CCC.GOOD_SPEC
,		CCC.ORDER_UNIT
--,		BBB1.BORGCD AS VENDORCD
--,		BBB1.BORGNM AS VENDORNM
,		BBB.SELL_PRICE AS SALE_PROD_PRIS

,		CCC.REPRE_GOOD
,		0 AS REPRE_GOOD_IDEN_NUMB
FROM	(
		SELECT	AA.*
		FROM	(
				SELECT	A.GOOD_IDEN_NUMB
				--,		A.VENDORID
				FROM	MCGOODDISPLAY A
				WHERE	A.DISPLAY_TYPE = '20'
				AND		A.DISPLAY_TYPE_CD = '53'
				AND		A.AGENT_ID = '13'
				UNION ALL
				SELECT	A.GOOD_IDEN_NUMB
				--,		A.VENDORID
				FROM	MCGOODDISPLAYBRANCH A
				WHERE	A.BRANCHID IN (SELECT BORGID FROM SMPBORGS WHERE PARBORGID = '305786' AND ISUSE = '1')
		) AA
		GROUP BY AA.GOOD_IDEN_NUMB--, AA.VENDORID
) AAA
INNER JOIN MCGOODVENDOR BBB
	ON	BBB.GOOD_IDEN_NUMB = AAA.GOOD_IDEN_NUMB
	--AND	BBB.VENDORID = AAA.VENDORID
--INNER JOIN SMPBORGS BBB1
	--ON	BBB1.BORGID = AAA.VENDORID
INNER JOIN MCGOOD CCC
	ON	CCC.GOOD_IDEN_NUMB = AAA.GOOD_IDEN_NUMB
WHERE	BBB.ISUSE = '1'
ORDER BY REPRE_GOOD, GOOD_IDEN_NUMB


SELECT	ZZ.*
FROM	(
		SELECT	Z.GOOD_IDEN_NUMB
		,		Z.GOOD_NAME
		,		Z.GOOD_SPEC
		,		Z.ORDER_UNIT
		,		(SELECT MAX(X.SELL_PRICE) FROM MCGOODVENDOR X WHERE X.GOOD_IDEN_NUMB = Z.GOOD_IDEN_NUMB AND X.ISUSE = '1' AND ISNULL(X.SELL_PRICE,0) > 0) AS SALE_PROD_PRIS
		,		'P' AS REPRE_GOOD
		,		Z.REPRE_GOOD_IDEN_NUMB
		FROM	MCGOOD Z
		WHERE	REPRE_GOOD_IDEN_NUMB IN (
				SELECT	DISTINCT
						CCC.GOOD_IDEN_NUMB
				FROM	(
						SELECT	AA.*
						FROM	(
								SELECT	A.GOOD_IDEN_NUMB
								FROM	MCGOODDISPLAY A
								WHERE	A.DISPLAY_TYPE = '20'
								AND		A.DISPLAY_TYPE_CD = '53'
								AND		A.AGENT_ID = '13'
								UNION ALL
								SELECT	A.GOOD_IDEN_NUMB
								FROM	MCGOODDISPLAYBRANCH A
								WHERE	A.BRANCHID IN (SELECT BORGID FROM SMPBORGS WHERE PARBORGID = '305786' AND ISUSE = '1')
						) AA
						GROUP BY AA.GOOD_IDEN_NUMB
				) AAA
				INNER JOIN MCGOODVENDOR BBB
					ON	BBB.GOOD_IDEN_NUMB = AAA.GOOD_IDEN_NUMB
				INNER JOIN MCGOOD CCC
					ON	CCC.GOOD_IDEN_NUMB = AAA.GOOD_IDEN_NUMB
				WHERE	BBB.ISUSE = '1'
				AND		CCC.REPRE_GOOD = 'Y'
		)
) ZZ
WHERE	ZZ.SALE_PROD_PRIS>0
ORDER BY ZZ.REPRE_GOOD_IDEN_NUMB
