SELECT 	A.CUST_CODE 
,		A.CUST_TYPE1 
,		A.CUST_TYPE2 
,		A.CUST_NAME
,		A.REGNUM
,		A.PRES_NAME
,		A.PRES_JUMIN_NO
,		A.TEL
,		A.FAX
,		A.ZIPCODE
,		A.ADDR
,		A.ADDR_DETAIL
,		A.CAPITAL
,		A.FOUND_YEAR
,		CASE 	WHEN A.CERT_YN!='Y' AND A.ETC!='xxx' THEN 'D'
				ELSE A.CERT_YN
		END AS CERT_YN
,		A.ETC
,		A.CREATE_USER
,		A.CREATE_DATE
,		A.UPDATE_USER
,		A.UPDATE_DATE
,		A.INTERRELATED_CUST_CODE
,		A.B_FILE	-- 회사소개서
,		CASE 	WHEN A.B_FILE IS NOT NULL 
				THEN 'intro/' || A.B_FILE 
		END AS B_FILE_PATH -- 회사소개서 경로
FROM 	T_CO_CUST_MASTER A