SELECT	A.USER_ID
,		A.CUST_CODE 
,		NULL AS USER_PWD -- 로그인 시 구시스템 조회
,		A.USER_NAME 
,		A.USER_TEL 
,		A.USER_HP 
,		A.USER_EMAIL 
,		A.USER_TYPE 
,		A.USER_BUSEO 
,		A.USER_POSITION 
,		A.CREATE_USER 
,		A.CREATE_DATE 
,		'Y' AS USE_YN
FROM 	T_CO_CUST_USER A

