SELECT	FILE_ID
,		KEY1 AS BI_NO
,		CASE	WHEN KEY2 IS NOT NULL THEN KEY2
				WHEN KEY3 IS NOT NULL THEN KEY3
				ELSE 'C'
		END AS FILE_FLAG
,		F_CUST_CODE
,		ORGINFILE AS FILE_NM
,		REPLACE( REPLACE(REALFILE,'D:\EBID_SYSTEM\UPLOAD\ebid\',''), '\', '/') || '/' || ORGINFILE AS FILE_PATH
,		WRITEDATE AS CREATE_DATE
,		'Y' AS USE_YN
FROM	T_CO_UPLOAD T_BI_UPLOAD

