SELECT	A.BI_NO 
,		A.CUST_CODE 
,		A.REBID_ATT 
,		A.ESMT_YN
,		A.ESMT_AMT
,		A.SUCC_YN 
,		A.FILE_ID 
,		A.SUBMIT_DATE 
,		A.CREATE_USER 
,		A.CREATE_DATE 
,		A.UPDATE_USER 
,		A.UPDATE_DATE 
,		A.BI_ORDER 
,		A.ESMT_CURR 
,		A.ETC_B_FILE 
,		CASE WHEN A.ETC_B_FILE IS NOT NULL 
				THEN 'file_etc/'||A.ETC_B_FILE
		END AS ETC_B_FILE_PATH
-- ,		A.ENC_QUTN
-- ,		A.ENC_QUTN_SUB 
,		TO_CLOB(A.ENC_QUTN) || TO_CLOB(A.ENC_QUTN_SUB) AS ENC_QUTN 
,		A.ENC_ESMT_SPEC 
-- ,		A.FILE_HASH_VALUE 
,		A.USEMAIL_ID 
FROM 	T_BI_INFO_MAT_CUST A
-- ORDER BY A.CREATE_DATE DESC 

